/**
 * Exportador de STL Binário
 * Converte geometria Three.js para formato STL binário
 */

import * as THREE from 'three';
import { writeFile } from 'fs/promises';
import path from 'path';

export class STLExporter {
  /**
   * Exporta geometria para STL binário
   */
  public static export(geometry: THREE.BufferGeometry, name: string = 'insole'): ArrayBuffer {
    console.log(`[STLExporter] Exporting ${name} to STL binary format...`);
    
    // Garantir que temos índices
    if (!geometry.index) {
      geometry = geometry.toNonIndexed();
    }
    
    const positions = geometry.attributes.position;
    const normals = geometry.attributes.normal;
    
    if (!normals) {
      geometry.computeVertexNormals();
    }
    
    const triangles = geometry.index ? geometry.index.count / 3 : positions.count / 3;
    
    // STL binário format:
    // 80 bytes: header
    // 4 bytes: número de triângulos (uint32)
    // Para cada triângulo (50 bytes):
    //   12 bytes: normal (3x float32)
    //   36 bytes: vértices (9x float32)
    //   2 bytes: attribute byte count (uint16)
    
    const bufferSize = 80 + 4 + (triangles * 50);
    const buffer = new ArrayBuffer(bufferSize);
    const view = new DataView(buffer);
    
    // Header (80 bytes)
    const header = `BPR Clinic - ${name} - Generated by STLExporter`;
    for (let i = 0; i < 80; i++) {
      view.setUint8(i, i < header.length ? header.charCodeAt(i) : 0);
    }
    
    // Número de triângulos
    view.setUint32(80, triangles, true);
    
    // Triângulos
    let offset = 84;
    
    if (geometry.index) {
      // Geometria indexada
      const indices = geometry.index;
      const normalsAttr = geometry.attributes.normal;
      
      for (let i = 0; i < triangles; i++) {
        const i1 = indices.getX(i * 3);
        const i2 = indices.getX(i * 3 + 1);
        const i3 = indices.getX(i * 3 + 2);
        
        // Normal (usar normal do primeiro vértice)
        const nx = normalsAttr.getX(i1);
        const ny = normalsAttr.getY(i1);
        const nz = normalsAttr.getZ(i1);
        view.setFloat32(offset, nx, true); offset += 4;
        view.setFloat32(offset, ny, true); offset += 4;
        view.setFloat32(offset, nz, true); offset += 4;
        
        // Vértice 1
        view.setFloat32(offset, positions.getX(i1), true); offset += 4;
        view.setFloat32(offset, positions.getY(i1), true); offset += 4;
        view.setFloat32(offset, positions.getZ(i1), true); offset += 4;
        
        // Vértice 2
        view.setFloat32(offset, positions.getX(i2), true); offset += 4;
        view.setFloat32(offset, positions.getY(i2), true); offset += 4;
        view.setFloat32(offset, positions.getZ(i2), true); offset += 4;
        
        // Vértice 3
        view.setFloat32(offset, positions.getX(i3), true); offset += 4;
        view.setFloat32(offset, positions.getY(i3), true); offset += 4;
        view.setFloat32(offset, positions.getZ(i3), true); offset += 4;
        
        // Attribute byte count
        view.setUint16(offset, 0, true); offset += 2;
      }
    } else {
      // Geometria não indexada
      const normalsAttr = geometry.attributes.normal;
      
      for (let i = 0; i < triangles; i++) {
        const idx = i * 3;
        
        // Normal (usar normal do primeiro vértice)
        const nx = normalsAttr.getX(idx);
        const ny = normalsAttr.getY(idx);
        const nz = normalsAttr.getZ(idx);
        view.setFloat32(offset, nx, true); offset += 4;
        view.setFloat32(offset, ny, true); offset += 4;
        view.setFloat32(offset, nz, true); offset += 4;
        
        // Vértice 1
        view.setFloat32(offset, positions.getX(idx), true); offset += 4;
        view.setFloat32(offset, positions.getY(idx), true); offset += 4;
        view.setFloat32(offset, positions.getZ(idx), true); offset += 4;
        
        // Vértice 2
        view.setFloat32(offset, positions.getX(idx + 1), true); offset += 4;
        view.setFloat32(offset, positions.getY(idx + 1), true); offset += 4;
        view.setFloat32(offset, positions.getZ(idx + 1), true); offset += 4;
        
        // Vértice 3
        view.setFloat32(offset, positions.getX(idx + 2), true); offset += 4;
        view.setFloat32(offset, positions.getY(idx + 2), true); offset += 4;
        view.setFloat32(offset, positions.getZ(idx + 2), true); offset += 4;
        
        // Attribute byte count
        view.setUint16(offset, 0, true); offset += 2;
      }
    }
    
    console.log(`[STLExporter] ✓ Exported ${triangles} triangles (${(bufferSize / 1024).toFixed(1)} KB)`);
    
    return buffer;
  }
  
  /**
   * Salva STL em arquivo
   */
  public static async saveToFile(
    geometry: THREE.BufferGeometry,
    filename: string,
    uploadsDir?: string
  ): Promise<string> {
    const stlBuffer = this.export(geometry, filename);
    
    // Determinar diretório de uploads
    const baseDir = uploadsDir || process.env.UPLOADS_DIR || path.join(process.cwd(), 'public', 'uploads');
    const scansDir = path.join(baseDir, 'insoles');
    
    // Criar diretório se não existir
    const fs = require('fs').promises;
    try {
      await fs.mkdir(scansDir, { recursive: true });
    } catch (err) {
      // Diretório já existe
    }
    
    // Salvar arquivo
    const fullPath = path.join(scansDir, filename);
    await writeFile(fullPath, new Uint8Array(stlBuffer));
    
    // Retornar URL relativa
    const relativeUrl = `/uploads/insoles/${filename}`;
    
    console.log(`[STLExporter] ✓ Saved to ${fullPath}`);
    console.log(`[STLExporter] ✓ URL: ${relativeUrl}`);
    
    return relativeUrl;
  }
  
  /**
   * Converte ArrayBuffer para Base64 (para download direto)
   */
  public static toBase64(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    let binary = '';
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return Buffer.from(binary, 'binary').toString('base64');
  }
}
