const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function main() {
  // Get first clinic
  const clinic = await prisma.clinic.findFirst({ select: { id: true, name: true } });
  if (!clinic) {
    console.log("No clinic found!");
    return;
  }
  console.log(`Seeding marketplace for clinic: ${clinic.name} (${clinic.id})`);

  // Delete existing marketplace products for clean seed
  await prisma.marketplaceProduct.deleteMany({ where: { clinicId: clinic.id } });
  console.log("Cleared existing products.");

  // ─── OWN PRODUCTS ───
  const ownProducts = [
    {
      name: "BPR Plantar Fascia Massage Ball",
      shortDescription: "3D printed massage ball for plantar fascia and foot release",
      description: "Compact BPR in-house 3D printed massage ball designed for plantar fascia release, foot intrinsic activation and daily recovery. Produced on demand using durable material and sized for easy use at home, work or after training.",
      category: "equipment",
      price: 14.99,
      costPrice: 2.8,
      compareAtPrice: 19.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=300&fit=crop",
      sku: "BPR-3D-PFM-001",
      weight: 0.08,
      trackStock: true,
      stockQuantity: 40,
      lowStockAlert: 8,
      shippingCost: 2.99,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 120,
      creditsDiscount: 20,
      featured: true,
      tags: ["3d printed", "foot care", "massage ball", "plantar fascia"],
      sortOrder: 1,
    },
    {
      name: "BPR Toe Spacer Set",
      shortDescription: "Flexible 3D printed toe spacers for alignment and comfort",
      description: "Soft-touch 3D printed toe spacer set produced in-house to help reduce toe crowding, improve toe splay awareness and support foot comfort inside recovery footwear. Suitable for gradual daily use and home mobility routines.",
      category: "physical_product",
      price: 18.99,
      costPrice: 3.6,
      compareAtPrice: 24.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
      sku: "BPR-3D-TS-001",
      weight: 0.05,
      trackStock: true,
      stockQuantity: 55,
      lowStockAlert: 10,
      shippingCost: 2.99,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 150,
      creditsDiscount: 25,
      featured: true,
      tags: ["3d printed", "toe spacer", "alignment", "foot care"],
      sortOrder: 2,
    },
    {
      name: "BPR Metatarsal Support Pads",
      shortDescription: "3D printed forefoot pads to offload pressure in the metatarsal area",
      description: "Pair of lightweight BPR 3D printed metatarsal support pads designed to reduce forefoot discomfort and redistribute pressure during daily walking. Ideal as a simple add-on for shoes with removable insoles.",
      category: "physical_product",
      price: 22.99,
      costPrice: 4.4,
      compareAtPrice: 29.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=300&fit=crop",
      sku: "BPR-3D-MP-001",
      weight: 0.09,
      trackStock: true,
      stockQuantity: 36,
      lowStockAlert: 8,
      shippingCost: 3.49,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 180,
      creditsDiscount: 30,
      featured: true,
      tags: ["3d printed", "metatarsal", "forefoot", "pressure relief"],
      sortOrder: 3,
    },
    {
      name: "BPR Heel Lift Wedges",
      shortDescription: "Printed-to-order heel wedges for gradual offloading and support",
      description: "BPR heel lift wedges are produced in-house and designed for short-term use where slight heel elevation is helpful for comfort, calf unloading or footwear balancing. Delivered as a pair with fitting guidance.",
      category: "physical_product",
      price: 19.99,
      costPrice: 3.9,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=300&fit=crop",
      sku: "BPR-3D-HW-001",
      weight: 0.12,
      trackStock: true,
      stockQuantity: 30,
      lowStockAlert: 6,
      shippingCost: 3.49,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 160,
      creditsDiscount: 25,
      tags: ["3d printed", "heel lift", "wedge", "support"],
      sortOrder: 4,
    },
    {
      name: "BPR Bunion Comfort Guard",
      shortDescription: "Protective 3D printed hallux valgus comfort shield",
      description: "Flexible BPR in-house 3D printed comfort guard designed to reduce rubbing around the bunion area and improve comfort in wider footwear. Best suited for comfort support and low-irritation daily wear.",
      category: "physical_product",
      price: 21.99,
      costPrice: 4.1,
      compareAtPrice: 27.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=300&fit=crop",
      sku: "BPR-3D-BCG-001",
      weight: 0.06,
      trackStock: true,
      stockQuantity: 28,
      lowStockAlert: 6,
      shippingCost: 3.49,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 170,
      creditsDiscount: 25,
      tags: ["3d printed", "bunion", "hallux valgus", "foot care"],
      sortOrder: 5,
    },
    {
      name: "BPR Recovery Grip Handle",
      shortDescription: "3D printed ergonomic handle for bands and rehab drills",
      description: "Ergonomic 3D printed grip handle made by BPR for resistance band exercises, grip retraining and home rehab sessions. Designed to improve comfort and control for patients who dislike narrow strap handles.",
      category: "equipment",
      price: 16.99,
      costPrice: 3.2,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?w=400&h=300&fit=crop",
      sku: "BPR-3D-RGH-001",
      weight: 0.11,
      trackStock: true,
      stockQuantity: 34,
      lowStockAlert: 8,
      shippingCost: 3.49,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 140,
      creditsDiscount: 20,
      tags: ["3d printed", "grip", "handle", "rehab tools"],
      sortOrder: 6,
    },
    {
      name: "BPR Trigger Release Tool",
      shortDescription: "Compact 3D printed trigger tool for calves, feet and forearms",
      description: "Printed in-house for targeted self-release work, this BPR trigger release tool helps patients apply controlled pressure to calf muscles, plantar tissues and forearm trigger points without hand fatigue.",
      category: "equipment",
      price: 24.99,
      costPrice: 5.3,
      compareAtPrice: 31.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=300&fit=crop",
      sku: "BPR-3D-TRT-001",
      weight: 0.16,
      trackStock: true,
      stockQuantity: 24,
      lowStockAlert: 5,
      shippingCost: 3.99,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 200,
      creditsDiscount: 30,
      tags: ["3d printed", "trigger point", "massage", "rehab tools"],
      sortOrder: 7,
    },
    {
      name: "BPR Finger Support Splint",
      shortDescription: "Lightweight printed finger splint for guided support",
      description: "Minimal, lightweight BPR finger support splint produced on demand for gentle support during recovery routines. Designed as a comfort support accessory and best used according to professional advice.",
      category: "physical_product",
      price: 17.99,
      costPrice: 3.1,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=300&fit=crop",
      sku: "BPR-3D-FSS-001",
      weight: 0.03,
      trackStock: true,
      stockQuantity: 22,
      lowStockAlert: 5,
      shippingCost: 2.99,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 130,
      creditsDiscount: 20,
      tags: ["3d printed", "finger splint", "support", "hand rehab"],
      sortOrder: 8,
    },
    {
      name: "BPR Thumb Comfort Support",
      shortDescription: "Printed thumb support for light daily stability and comfort",
      description: "BPR thumb comfort support is a compact 3D printed accessory created for light day-to-day support where a lower-profile option is preferred. Printed to order and shipped with simple wear guidance.",
      category: "physical_product",
      price: 23.99,
      costPrice: 4.8,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1584515933487-779824d29309?w=400&h=300&fit=crop",
      sku: "BPR-3D-TCS-001",
      weight: 0.07,
      trackStock: true,
      stockQuantity: 20,
      lowStockAlert: 5,
      shippingCost: 3.49,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 180,
      creditsDiscount: 25,
      tags: ["3d printed", "thumb support", "brace", "hand rehab"],
      sortOrder: 9,
    },
    {
      name: "BPR Foot Mobility Wobble Base",
      shortDescription: "3D printed balance base for intrinsic foot and ankle drills",
      description: "In-house printed wobble base made for simple balance and foot stability drills at home. Useful for controlled intrinsic strengthening, ankle awareness and progressive loading in rehab programs.",
      category: "equipment",
      price: 29.99,
      costPrice: 6.5,
      compareAtPrice: 36.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1518611012118-fb2f0afc62a5?w=400&h=300&fit=crop",
      sku: "BPR-3D-WB-001",
      weight: 0.28,
      trackStock: true,
      stockQuantity: 18,
      lowStockAlert: 4,
      shippingCost: 4.99,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 240,
      creditsDiscount: 35,
      featured: true,
      tags: ["3d printed", "balance", "foot stability", "ankle rehab"],
      sortOrder: 10,
    },
    {
      name: "BPR Foot Anatomy Model",
      shortDescription: "Desktop 3D printed foot anatomy model for patient education",
      description: "Educational BPR 3D printed foot model used to help explain arch mechanics, plantar fascia irritation, bunions and loading patterns during treatment. Ideal for clinics, students and engaged patients.",
      category: "equipment",
      price: 34.99,
      costPrice: 8.2,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?w=400&h=300&fit=crop",
      sku: "BPR-3D-FAM-001",
      weight: 0.35,
      trackStock: true,
      stockQuantity: 14,
      lowStockAlert: 3,
      shippingCost: 4.99,
      freeShippingOver: 60,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 260,
      creditsDiscount: 40,
      tags: ["3d printed", "anatomy", "education", "foot model"],
      sortOrder: 11,
    },
    {
      name: "BPR Custom Orthotic Insole Assessment",
      shortDescription: "Start your custom 3D printed insole journey with BPR",
      description: "Entry product for patients who want a custom 3D printed orthotic pathway with BPR. Includes intake, scan review and product planning before final bespoke production. Best suited for patients who need a more personalised solution than standard accessories.",
      category: "special_session",
      price: 79.99,
      costPrice: 18,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=300&fit=crop",
      sku: "BPR-3D-COI-001",
      isDigital: false,
      shippingCost: 0,
      isAffiliate: false,
      creditsCost: 700,
      creditsDiscount: 120,
      featured: true,
      tags: ["custom", "orthotic", "insole", "assessment"],
      sortOrder: 12,
    },
    {
      name: "BPR Foot Care Starter Guide",
      shortDescription: "Digital guide to help patients choose the right BPR 3D foot products",
      description: "Short digital starter guide created by BPR to explain common foot discomfort patterns, how our 3D printed products are used and when a patient should move from standard supports to a custom assessment.",
      category: "digital_program",
      price: 7.99,
      costPrice: 0,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1513258496099-48168024aec0?w=400&h=300&fit=crop",
      sku: "BPR-DIG-FCG-001",
      isDigital: true,
      isAffiliate: false,
      creditsCost: 60,
      creditsDiscount: 10,
      tags: ["digital", "foot care", "guide", "education"],
      sortOrder: 13,
    },
    {
      name: "BPR Printed-to-Order Recovery Box",
      shortDescription: "Monthly box with rotating BPR 3D printed recovery tools",
      description: "A monthly BPR box featuring selected in-house 3D printed recovery tools, foot care accessories and a short therapist guide. Built for patients who want to keep progressing their home-care setup with new printed tools.",
      category: "subscription",
      price: 39.99,
      costPrice: 14,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1607082349566-187342175e2f?w=400&h=300&fit=crop",
      sku: "BPR-3D-BOX-001",
      weight: 0.9,
      trackStock: false,
      shippingCost: 0,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 320,
      creditsDiscount: 50,
      tags: ["subscription", "3d printed", "recovery box", "home care"],
      sortOrder: 14,
    },
  ];

  // ─── AMAZON AFFILIATE PRODUCTS ───
  const affiliateProducts = [
    {
      name: "TheraBand FlexBar — Resistance Bar",
      shortDescription: "Complementary clinician-recommended grip and elbow rehab tool",
      description: "A small curated external recommendation for patients who need an additional off-the-shelf rehab tool alongside BPR in-house printed products.",
      category: "equipment",
      price: 16.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=400&h=300&fit=crop",
      isAffiliate: true,
      affiliateUrl: "https://www.amazon.co.uk/dp/B000KGOMLS?tag=bpr-21",
      affiliateTag: "bpr-21",
      affiliateCommission: 4.5,
      amazonAsin: "B000KGOMLS",
      tags: ["recommended", "grip", "elbow rehab"],
      sortOrder: 20,
    },
    {
      name: "Yoga Mat — Extra Thick (15mm)",
      shortDescription: "Complementary floor exercise mat for home rehab work",
      description: "A simple curated add-on for patients doing home mobility and floor-based rehab alongside BPR printed tools.",
      category: "equipment",
      price: 21.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=300&fit=crop",
      isAffiliate: true,
      affiliateUrl: "https://www.amazon.co.uk/dp/B08CK5YLCR?tag=bpr-21",
      affiliateTag: "bpr-21",
      affiliateCommission: 4.0,
      amazonAsin: "B08CK5YLCR",
      tags: ["recommended", "exercise mat", "home rehab"],
      sortOrder: 21,
    },
  ];

  // Create all products
  const allProducts = [...ownProducts, ...affiliateProducts];

  for (const product of allProducts) {
    const slug = product.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    const costPrice = (product as any).costPrice ?? null;
    const price = product.price;
    const marginPercent = costPrice != null && costPrice > 0 && price > 0
      ? parseFloat(((price - costPrice) / price * 100).toFixed(2))
      : null;

    await prisma.marketplaceProduct.create({
      data: {
        clinicId: clinic.id,
        name: product.name,
        shortDescription: product.shortDescription || null,
        description: product.description || null,
        category: product.category,
        price: product.price,
        costPrice: costPrice,
        marginPercent,
        compareAtPrice: (product as any).compareAtPrice || null,
        currency: "GBP",
        vatRate: product.vatRate ?? 20,
        vatIncluded: product.vatIncluded !== false,
        imageUrl: product.imageUrl || null,
        sku: (product as any).sku || null,
        weight: (product as any).weight || null,
        trackStock: (product as any).trackStock || false,
        stockQuantity: (product as any).stockQuantity ?? null,
        lowStockAlert: (product as any).lowStockAlert || 5,
        shippingCost: (product as any).shippingCost || 0,
        freeShippingOver: (product as any).freeShippingOver || null,
        isDigital: (product as any).isDigital || false,
        isAffiliate: (product as any).isAffiliate || false,
        affiliateUrl: (product as any).affiliateUrl || null,
        affiliateTag: (product as any).affiliateTag || null,
        affiliateCommission: (product as any).affiliateCommission || null,
        amazonAsin: (product as any).amazonAsin || null,
        creditsCost: (product as any).creditsCost || 0,
        creditsDiscount: (product as any).creditsDiscount || 0,
        featured: (product as any).featured || false,
        tags: (product as any).tags || null,
        targetMinLevel: (product as any).targetMinLevel || null,
        targetConditions: (product as any).targetConditions || null,
        slug,
        isActive: true,
        sortOrder: product.sortOrder || 0,
      },
    });
    console.log(`  ✓ ${product.isAffiliate ? "[AFFILIATE]" : "[OWN]"} ${product.name}`);
  }

  console.log(`\nDone! Created ${allProducts.length} products (${ownProducts.length} own + ${affiliateProducts.length} affiliate)`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
