const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function main() {
  // Get first clinic
  const clinic = await prisma.clinic.findFirst({ select: { id: true, name: true } });
  if (!clinic) {
    console.log("No clinic found!");
    return;
  }
  console.log(`Seeding marketplace for clinic: ${clinic.name} (${clinic.id})`);

  // Delete existing marketplace products for clean seed
  await prisma.marketplaceProduct.deleteMany({ where: { clinicId: clinic.id } });
  console.log("Cleared existing products.");

  // ─── OWN PRODUCTS ───
  const ownProducts = [
    {
      name: "Resistance Band Set (3-Pack)",
      shortDescription: "Light, Medium & Heavy resistance bands for home rehab",
      description: "Professional-grade latex resistance bands perfect for physiotherapy exercises. Includes 3 levels: Light (yellow), Medium (green), Heavy (blue). Each band is 1.5m long with non-slip grip texture. Ideal for upper and lower body rehabilitation exercises prescribed by your therapist.",
      category: "equipment",
      price: 24.99,
      costPrice: 8.50,
      compareAtPrice: 34.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400&h=300&fit=crop",
      sku: "BPR-RB-003",
      weight: 0.35,
      trackStock: true,
      stockQuantity: 48,
      lowStockAlert: 10,
      shippingCost: 3.99,
      freeShippingOver: 50,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 200,
      creditsDiscount: 50,
      featured: true,
      tags: ["resistance", "bands", "home exercise", "rehab"],
      targetMinLevel: 2,
      sortOrder: 1,
    },
    {
      name: "Foam Roller — Deep Tissue",
      shortDescription: "High-density EVA foam roller for myofascial release",
      description: "Premium high-density EVA foam roller (45cm x 15cm) with textured surface for deep tissue massage and myofascial release. Helps reduce muscle soreness, improve flexibility and aid recovery between sessions. Recommended by our therapists for daily use.",
      category: "equipment",
      price: 19.99,
      costPrice: 6.20,
      compareAtPrice: 27.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1620188526357-8b58e131062c?w=400&h=300&fit=crop",
      sku: "BPR-FR-001",
      weight: 0.45,
      trackStock: true,
      stockQuantity: 32,
      lowStockAlert: 8,
      shippingCost: 4.99,
      freeShippingOver: 50,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 150,
      creditsDiscount: 30,
      featured: true,
      tags: ["foam roller", "massage", "recovery", "myofascial"],
      sortOrder: 2,
    },
    {
      name: "BPR Recovery Programme — 8 Weeks",
      shortDescription: "Complete digital recovery programme with video exercises",
      description: "Our signature 8-week digital recovery programme includes 40+ guided video exercises, weekly progression plans, nutrition tips, sleep optimisation guide, and direct messaging with your therapist. New content unlocked each week based on your progress. Accessible on any device.",
      category: "digital_program",
      price: 49.99,
      costPrice: 0,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop",
      sku: "BPR-DP-001",
      isDigital: true,
      isAffiliate: false,
      creditsCost: 500,
      creditsDiscount: 100,
      featured: true,
      tags: ["programme", "digital", "video", "8 weeks", "recovery"],
      targetMinLevel: 3,
      sortOrder: 3,
    },
    {
      name: "Posture Correction Guide (PDF)",
      shortDescription: "48-page illustrated guide to improve your posture daily",
      description: "Comprehensive 48-page digital guide with illustrated exercises, desk setup tips, sleeping position advice and daily posture habits. Written by our senior physiotherapist. Includes printable wall charts and a 30-day challenge checklist.",
      category: "digital_program",
      price: 9.99,
      costPrice: 0,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop",
      sku: "BPR-PG-001",
      isDigital: true,
      isAffiliate: false,
      creditsCost: 80,
      creditsDiscount: 20,
      tags: ["posture", "guide", "pdf", "exercises"],
      sortOrder: 4,
    },
    {
      name: "Sports Massage — 60min Session",
      shortDescription: "Deep tissue sports massage by qualified therapist",
      description: "Professional 60-minute deep tissue sports massage session at our clinic. Targets muscle tension, reduces pain, improves range of motion and accelerates recovery. Performed by our qualified sports massage therapist. Must be booked separately after purchase.",
      category: "special_session",
      price: 65.00,
      costPrice: 20.00,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400&h=300&fit=crop",
      sku: "BPR-SM-060",
      isDigital: false,
      shippingCost: 0,
      isAffiliate: false,
      creditsCost: 600,
      creditsDiscount: 100,
      featured: true,
      tags: ["massage", "sports", "deep tissue", "session"],
      targetMinLevel: 5,
      sortOrder: 5,
    },
    {
      name: "Magnesium Glycinate — 120 Capsules",
      shortDescription: "High-absorption magnesium for muscle recovery & sleep",
      description: "Premium magnesium glycinate supplement (400mg per serving). Highly bioavailable form for optimal absorption. Supports muscle recovery, reduces cramps, improves sleep quality and reduces stress. 60-day supply. Made in the UK, GMP certified.",
      category: "supplement",
      price: 18.99,
      costPrice: 7.50,
      compareAtPrice: 24.99,
      vatRate: 0,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop",
      sku: "BPR-MG-120",
      weight: 0.18,
      trackStock: true,
      stockQuantity: 65,
      lowStockAlert: 15,
      shippingCost: 2.99,
      freeShippingOver: 30,
      isDigital: false,
      isAffiliate: false,
      tags: ["magnesium", "supplement", "recovery", "sleep"],
      sortOrder: 6,
    },
    {
      name: "Monthly Recovery Subscription",
      shortDescription: "Monthly box with exercises, tips & small equipment",
      description: "Monthly subscription box delivered to your door. Each month includes: 1 piece of rehab equipment, printed exercise cards, recovery tips newsletter, exclusive video content access, and 100 bonus BPR Credits. Cancel anytime. First box ships within 3 business days.",
      category: "subscription",
      price: 29.99,
      costPrice: 12.00,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1607082349566-187342175e2f?w=400&h=300&fit=crop",
      sku: "BPR-SUB-M",
      weight: 1.2,
      trackStock: false,
      shippingCost: 0,
      isDigital: false,
      isAffiliate: false,
      creditsCost: 250,
      tags: ["subscription", "monthly", "box", "recovery"],
      featured: true,
      targetMinLevel: 4,
      sortOrder: 7,
    },
    {
      name: "Kinesiology Tape — 5m Roll",
      shortDescription: "Elastic therapeutic tape for joint & muscle support",
      description: "Professional kinesiology tape (5m x 5cm) in blue. Hypoallergenic, water-resistant, latex-free. Provides support to muscles and joints without restricting movement. Pre-cut strips for easy self-application. Instructions included.",
      category: "physical_product",
      price: 8.99,
      costPrice: 2.80,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=400&h=300&fit=crop",
      sku: "BPR-KT-005",
      weight: 0.12,
      trackStock: true,
      stockQuantity: 120,
      lowStockAlert: 20,
      shippingCost: 1.99,
      freeShippingOver: 30,
      isDigital: false,
      isAffiliate: false,
      tags: ["tape", "kinesiology", "support", "muscle"],
      sortOrder: 8,
    },
  ];

  // ─── AMAZON AFFILIATE PRODUCTS ───
  const affiliateProducts = [
    {
      name: "TheraBand FlexBar — Resistance Bar",
      shortDescription: "Clinically proven for tennis elbow & grip strength",
      description: "The TheraBand FlexBar is clinically proven to help treat and prevent tennis elbow (lateral epicondylitis). Made of dry natural rubber, it provides progressive resistance for upper extremity strengthening. Used in the Tyler Twist protocol recommended by physiotherapists worldwide.",
      category: "equipment",
      price: 16.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=400&h=300&fit=crop",
      isAffiliate: true,
      affiliateUrl: "https://www.amazon.co.uk/dp/B000KGOMLS?tag=bpr-21",
      affiliateTag: "bpr-21",
      affiliateCommission: 4.5,
      amazonAsin: "B000KGOMLS",
      creditsCost: 0,
      featured: true,
      tags: ["theraband", "flexbar", "tennis elbow", "grip"],
      targetConditions: { painScore: ">3" },
      sortOrder: 10,
    },
    {
      name: "Trigger Point Massage Ball Set",
      shortDescription: "3 density levels for targeted myofascial release",
      description: "Set of 3 lacrosse-style massage balls with different densities (soft, medium, firm). Perfect for targeting trigger points, plantar fascia, shoulders, glutes and back. Compact and portable — ideal for home use or travel. Carry bag included.",
      category: "equipment",
      price: 12.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=300&fit=crop",
      isAffiliate: true,
      affiliateUrl: "https://www.amazon.co.uk/dp/B07KQLB12X?tag=bpr-21",
      affiliateTag: "bpr-21",
      affiliateCommission: 4.0,
      amazonAsin: "B07KQLB12X",
      tags: ["massage ball", "trigger point", "myofascial"],
      sortOrder: 11,
    },
    {
      name: "Compex Mini Wireless Muscle Stimulator",
      shortDescription: "Portable EMS device for pain relief & muscle recovery",
      description: "The Compex Mini is a wireless, portable muscle stimulator with 4 programmes: Pain Relief, Recovery, Warm-Up, and Muscle Strengthening. Bluetooth connectivity with free app. FDA cleared. Clinically proven TENS/EMS technology. Rechargeable battery lasts 6+ hours.",
      category: "equipment",
      price: 199.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=300&fit=crop",
      isAffiliate: true,
      affiliateUrl: "https://www.amazon.co.uk/dp/B08MQHX6GN?tag=bpr-21",
      affiliateTag: "bpr-21",
      affiliateCommission: 3.5,
      amazonAsin: "B08MQHX6GN",
      featured: true,
      tags: ["compex", "ems", "tens", "electrostimulation", "wireless"],
      targetMinLevel: 5,
      sortOrder: 12,
    },
    {
      name: "Pilates Ring — Dual Grip",
      shortDescription: "Resistance ring for core, thighs & upper body toning",
      description: "14-inch Pilates resistance ring with padded dual grips. Provides gentle resistance for toning exercises targeting inner/outer thighs, core, chest and arms. Lightweight and portable. Perfect complement to physiotherapy exercises. Non-slip pads for comfort.",
      category: "equipment",
      price: 14.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&h=300&fit=crop",
      isAffiliate: true,
      affiliateUrl: "https://www.amazon.co.uk/dp/B07N4M3GPJ?tag=bpr-21",
      affiliateTag: "bpr-21",
      affiliateCommission: 4.0,
      amazonAsin: "B07N4M3GPJ",
      tags: ["pilates", "ring", "core", "toning"],
      sortOrder: 13,
    },
    {
      name: "TENS Machine — Dual Channel",
      shortDescription: "Professional TENS unit for pain management at home",
      description: "Dual-channel TENS machine with 8 electrode pads, 25 intensity levels and 8 massage modes. Rechargeable battery, portable design. Effective for back pain, neck pain, arthritis, sciatica, and muscle soreness. LCD display with timer. Includes carry case and user guide.",
      category: "equipment",
      price: 29.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=300&fit=crop",
      isAffiliate: true,
      affiliateUrl: "https://www.amazon.co.uk/dp/B09BVMTGSZ?tag=bpr-21",
      affiliateTag: "bpr-21",
      affiliateCommission: 4.5,
      amazonAsin: "B09BVMTGSZ",
      featured: true,
      tags: ["tens", "pain relief", "electrotherapy", "muscle"],
      targetConditions: { painScore: ">5" },
      sortOrder: 14,
    },
    {
      name: "Omega-3 Fish Oil — 240 Softgels",
      shortDescription: "High-strength EPA/DHA for joint & inflammation support",
      description: "Triple-strength Omega-3 fish oil supplement. Each softgel provides 1000mg EPA + 500mg DHA. Molecularly distilled for purity. Supports joint health, reduces inflammation, and aids cardiovascular health. 4-month supply. Lemon-flavoured to reduce fishy aftertaste.",
      category: "supplement",
      price: 22.99,
      vatRate: 0,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&h=300&fit=crop",
      isAffiliate: true,
      affiliateUrl: "https://www.amazon.co.uk/dp/B01GV4O37E?tag=bpr-21",
      affiliateTag: "bpr-21",
      affiliateCommission: 5.0,
      amazonAsin: "B01GV4O37E",
      tags: ["omega-3", "fish oil", "joints", "inflammation"],
      sortOrder: 15,
    },
    {
      name: "Yoga Mat — Extra Thick (15mm)",
      shortDescription: "Non-slip exercise mat perfect for home physio exercises",
      description: "Extra thick (15mm) NBR foam yoga/exercise mat. Provides superior cushioning for joints during floor exercises. Non-slip textured surface on both sides. Includes carry strap. 183cm x 61cm. Ideal for home physiotherapy exercises, yoga, Pilates and stretching.",
      category: "equipment",
      price: 21.99,
      vatRate: 20,
      vatIncluded: true,
      imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=300&fit=crop",
      isAffiliate: true,
      affiliateUrl: "https://www.amazon.co.uk/dp/B08CK5YLCR?tag=bpr-21",
      affiliateTag: "bpr-21",
      affiliateCommission: 4.0,
      amazonAsin: "B08CK5YLCR",
      tags: ["yoga mat", "exercise mat", "home exercise"],
      sortOrder: 16,
    },
  ];

  // Create all products
  const allProducts = [...ownProducts, ...affiliateProducts];

  for (const product of allProducts) {
    const slug = product.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    const costPrice = (product as any).costPrice ?? null;
    const price = product.price;
    const marginPercent = costPrice != null && costPrice > 0 && price > 0
      ? parseFloat(((price - costPrice) / price * 100).toFixed(2))
      : null;

    await prisma.marketplaceProduct.create({
      data: {
        clinicId: clinic.id,
        name: product.name,
        shortDescription: product.shortDescription || null,
        description: product.description || null,
        category: product.category,
        price: product.price,
        costPrice: costPrice,
        marginPercent,
        compareAtPrice: (product as any).compareAtPrice || null,
        currency: "GBP",
        vatRate: product.vatRate ?? 20,
        vatIncluded: product.vatIncluded !== false,
        imageUrl: product.imageUrl || null,
        sku: (product as any).sku || null,
        weight: (product as any).weight || null,
        trackStock: (product as any).trackStock || false,
        stockQuantity: (product as any).stockQuantity ?? null,
        lowStockAlert: (product as any).lowStockAlert || 5,
        shippingCost: (product as any).shippingCost || 0,
        freeShippingOver: (product as any).freeShippingOver || null,
        isDigital: (product as any).isDigital || false,
        isAffiliate: (product as any).isAffiliate || false,
        affiliateUrl: (product as any).affiliateUrl || null,
        affiliateTag: (product as any).affiliateTag || null,
        affiliateCommission: (product as any).affiliateCommission || null,
        amazonAsin: (product as any).amazonAsin || null,
        creditsCost: (product as any).creditsCost || 0,
        creditsDiscount: (product as any).creditsDiscount || 0,
        featured: (product as any).featured || false,
        tags: (product as any).tags || null,
        targetMinLevel: (product as any).targetMinLevel || null,
        targetConditions: (product as any).targetConditions || null,
        slug,
        isActive: true,
        sortOrder: product.sortOrder || 0,
      },
    });
    console.log(`  ✓ ${product.isAffiliate ? "[AFFILIATE]" : "[OWN]"} ${product.name}`);
  }

  console.log(`\nDone! Created ${allProducts.length} products (${ownProducts.length} own + ${affiliateProducts.length} affiliate)`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
