import nodemailer from 'nodemailer';
import { getConfigValue } from '@/lib/system-config';

let _transporter: nodemailer.Transporter | null = null;
let _transporterTimestamp = 0;
const TRANSPORTER_TTL = 300_000; // 5 min

async function getSmtpTransporter(): Promise<nodemailer.Transporter | null> {
    if (_transporter && Date.now() - _transporterTimestamp < TRANSPORTER_TTL) {
        return _transporter;
    }
    const host = await getConfigValue('SMTP_HOST');
    const port = await getConfigValue('SMTP_PORT');
    const user = await getConfigValue('SMTP_USER');
    const pass = await getConfigValue('SMTP_PASS');

    if (!host || !user || !pass) return null;

    const portNum = parseInt(port || '465', 10);
    _transporter = nodemailer.createTransport({
        host,
        port: portNum,
        secure: portNum === 465,
        auth: { user, pass },
        tls: { rejectUnauthorized: false },
    });
    _transporterTimestamp = Date.now();
    return _transporter;
}

export async function sendEmail({
    to,
    subject,
    html,
    from,
    replyTo,
}: {
    to: string;
    subject: string;
    html: string;
    from?: string;
    replyTo?: string;
}) {
    const defaultFrom = (await getConfigValue('EMAIL_FROM')) || process.env.EMAIL_FROM || 'Bruno Physical Rehabilitation <support@bpr.rehab>';
    const fromAddr = from || defaultFrom;

    // Try SMTP (Hostinger) first
    try {
        const transporter = await getSmtpTransporter();
        if (transporter) {
            const info = await transporter.sendMail({ from: fromAddr, to, subject, html, replyTo: replyTo || undefined });
            console.log('[EMAIL] Sent via SMTP:', info.messageId);
            return { success: true, data: { messageId: info.messageId } };
        }
    } catch (smtpErr) {
        console.warn('[EMAIL] SMTP failed, trying Resend fallback:', smtpErr);
    }

    // Fallback to Resend
    try {
        const resendKey = (await getConfigValue('RESEND_API_KEY')) || process.env.RESEND_API_KEY;
        if (resendKey) {
            const { Resend } = await import('resend');
            const resend = new Resend(resendKey);
            const data = await resend.emails.send({ from: fromAddr, to, subject, html });
            console.log('[EMAIL] Sent via Resend');
            return { success: true, data };
        }
    } catch (resendErr) {
        console.error('[EMAIL] Resend fallback also failed:', resendErr);
    }

    console.error('[EMAIL] No email provider configured. Set SMTP or Resend in API Settings.');
    return { success: false, error: 'No email provider configured' };
}

export const emailTemplates = {
    forgotPassword: (resetUrl: string, name: string) => `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
      <h2 style="color: #607d7d;">Password Reset Request</h2>
      <p>Hi ${name},</p>
      <p>We received a request to reset your password. Click the button below to set a new one:</p>
      <div style="text-align: center; margin: 30px 0;">
        <a href="${resetUrl}" style="background-color: #5dc9c0; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold;">Reset Password</a>
      </div>
      <p>If you did not request this, you can safely ignore this email.</p>
      <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
      <p style="font-size: 12px; color: #999;">This link will expire in 1 hour.</p>
    </div>
  `,
    highRiskAlert: (patientName: string, redFlags: string[], adminUrl: string) => `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ff4d4f; border-radius: 10px; background-color: #fff1f0;">
      <h2 style="color: #cf1322;">High-Risk Patient Alert 🚩</h2>
      <p>A new medical screening has been submitted with critical red flags.</p>
      <div style="background-color: white; padding: 15px; border-radius: 5px; margin: 20px 0;">
        <p><strong>Patient:</strong> ${patientName}</p>
        <p><strong>Detected Red Flags:</strong></p>
        <ul>
          ${redFlags.map(flag => `<li style="color: #cf1322;">${flag}</li>`).join('')}
        </ul>
      </div>
      <div style="text-align: center; margin: 30px 0;">
        <a href="${adminUrl}" style="background-color: #cf1322; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold;">Review Patient Files</a>
      </div>
      <p style="font-size: 13px;">This alert was automatically generated by the clinical analysis engine.</p>
    </div>
  `,
    accountCreated: (name: string, loginUrl: string) => `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
      <h2 style="color: #607d7d;">Account Created Successfully</h2>
      <p>Hi ${name},</p>
      <p>Your account at Bruno Rehab has been created. You can now log in to the system:</p>
      <div style="text-align: center; margin: 30px 0;">
        <a href="${loginUrl}" style="background-color: #5dc9c0; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold;">Log In Now</a>
      </div>
    </div>
  `,
    serverAlert: (status: "down" | "recovered", details: string, dashboardUrl: string) => `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid ${status === "down" ? "#ff4d4f" : "#52c41a"}; border-radius: 10px; background-color: ${status === "down" ? "#fff1f0" : "#f6ffed"};">
      <h2 style="color: ${status === "down" ? "#cf1322" : "#389e0d"};">
        ${status === "down" ? "Server Alert: Service Degraded" : "Server Recovered: All Systems Normal"}
      </h2>
      <p>${status === "down"
        ? "The clinic system has detected issues that may affect service availability."
        : "The clinic system has recovered and is now functioning normally."}</p>
      <div style="background-color: white; padding: 15px; border-radius: 5px; margin: 20px 0;">
        <p><strong>Status:</strong> ${status === "down" ? "Degraded" : "Healthy"}</p>
        <p><strong>Time:</strong> ${new Date().toLocaleString("en-GB", { timeZone: "Europe/London" })}</p>
        <p><strong>Details:</strong> ${details}</p>
      </div>
      <div style="text-align: center; margin: 30px 0;">
        <a href="${dashboardUrl}" style="background-color: ${status === "down" ? "#cf1322" : "#389e0d"}; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold;">View System Logs</a>
      </div>
      <p style="font-size: 12px; color: #999;">This is an automated alert from the clinic monitoring system.</p>
    </div>
  `,
    verification: (verifyUrl: string, name: string) => `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
      <h2 style="color: #607d7d;">Verify Your Email</h2>
      <p>Hi ${name},</p>
      <p>Welcome to Bruno Rehab! Please verify your email address by clicking the button below:</p>
      <div style="text-align: center; margin: 30px 0;">
        <a href="${verifyUrl}" style="background-color: #5dc9c0; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold;">Verify Email</a>
      </div>
      <p>Once verified, you'll have full access to your clinical dashboard.</p>
    </div>
  `,
};
