/**
 * Default HMRC / Companies House aligned financial categories
 * Based on CT600 Corporation Tax Return and FRS 102/105 Annual Accounts
 */

export interface HmrcCategory {
  type: "INCOME" | "EXPENSE";
  name: string;
  nameEn: string;
  namePt: string;
  hmrcCode: string;
  hmrcLabel: string;
  companiesHouseSection: string;
  ct600Box: string;
  isTaxDeductible: boolean;
  description: string;
  sortOrder: number;
}

export const HMRC_DEFAULT_CATEGORIES: HmrcCategory[] = [
  // ─── INCOME CATEGORIES ───
  {
    type: "INCOME",
    name: "Turnover / Sales",
    nameEn: "Turnover / Sales",
    namePt: "Faturamento / Vendas",
    hmrcCode: "TURNOVER",
    hmrcLabel: "Turnover from trade",
    companiesHouseSection: "PL/Turnover",
    ct600Box: "Box 145",
    isTaxDeductible: false,
    description: "Main business income from physiotherapy services, consultations, and treatments",
    sortOrder: 1,
  },
  {
    type: "INCOME",
    name: "Treatment Packages",
    nameEn: "Treatment Packages",
    namePt: "Pacotes de Tratamento",
    hmrcCode: "TURNOVER/PACKAGES",
    hmrcLabel: "Turnover - service packages",
    companiesHouseSection: "PL/Turnover",
    ct600Box: "Box 145",
    isTaxDeductible: false,
    description: "Income from treatment packages and session bundles",
    sortOrder: 2,
  },
  {
    type: "INCOME",
    name: "Membership Subscriptions",
    nameEn: "Membership Subscriptions",
    namePt: "Assinaturas de Membros",
    hmrcCode: "TURNOVER/SUBS",
    hmrcLabel: "Turnover - subscriptions",
    companiesHouseSection: "PL/Turnover",
    ct600Box: "Box 145",
    isTaxDeductible: false,
    description: "Recurring membership and subscription income",
    sortOrder: 3,
  },
  {
    type: "INCOME",
    name: "Product Sales",
    nameEn: "Product Sales",
    namePt: "Venda de Produtos",
    hmrcCode: "TURNOVER/PRODUCTS",
    hmrcLabel: "Turnover - product sales",
    companiesHouseSection: "PL/Turnover",
    ct600Box: "Box 145",
    isTaxDeductible: false,
    description: "Income from selling health products, supplements, equipment",
    sortOrder: 4,
  },
  {
    type: "INCOME",
    name: "Assessments & Scans",
    nameEn: "Assessments & Scans",
    namePt: "Avaliações e Escaneamentos",
    hmrcCode: "TURNOVER/ASSESS",
    hmrcLabel: "Turnover - assessments",
    companiesHouseSection: "PL/Turnover",
    ct600Box: "Box 145",
    isTaxDeductible: false,
    description: "Income from body assessments, foot scans, and diagnostic services",
    sortOrder: 5,
  },
  {
    type: "INCOME",
    name: "Other Operating Income",
    nameEn: "Other Operating Income",
    namePt: "Outras Receitas Operacionais",
    hmrcCode: "OTHER_INCOME",
    hmrcLabel: "Other income from trade",
    companiesHouseSection: "PL/OtherOperatingIncome",
    ct600Box: "Box 155",
    isTaxDeductible: false,
    description: "Miscellaneous business income not covered by other categories",
    sortOrder: 6,
  },
  {
    type: "INCOME",
    name: "Interest Received",
    nameEn: "Interest Received",
    namePt: "Juros Recebidos",
    hmrcCode: "INTEREST_RECEIVED",
    hmrcLabel: "Interest and investment income",
    companiesHouseSection: "PL/InterestReceivable",
    ct600Box: "Box 160",
    isTaxDeductible: false,
    description: "Interest from bank accounts and investments",
    sortOrder: 7,
  },

  // ─── EXPENSE CATEGORIES ───
  {
    type: "EXPENSE",
    name: "Cost of Sales",
    nameEn: "Cost of Sales",
    namePt: "Custo dos Serviços",
    hmrcCode: "COS",
    hmrcLabel: "Cost of sales",
    companiesHouseSection: "PL/CostOfSales",
    ct600Box: "Box 146",
    isTaxDeductible: true,
    description: "Direct costs of delivering services: consumables, session materials",
    sortOrder: 10,
  },
  {
    type: "EXPENSE",
    name: "Staff Costs",
    nameEn: "Staff Costs",
    namePt: "Custos com Pessoal",
    hmrcCode: "STAFF",
    hmrcLabel: "Employee costs",
    companiesHouseSection: "PL/StaffCosts",
    ct600Box: "Box 63",
    isTaxDeductible: true,
    description: "Salaries, wages, NI contributions, pension, staff training",
    sortOrder: 11,
  },
  {
    type: "EXPENSE",
    name: "Subcontractors / Freelancers",
    nameEn: "Subcontractors / Freelancers",
    namePt: "Subcontratados / Freelancers",
    hmrcCode: "SUBCONTRACT",
    hmrcLabel: "Sub-contractor costs",
    companiesHouseSection: "PL/CostOfSales",
    ct600Box: "Box 64",
    isTaxDeductible: true,
    description: "Payments to subcontracted therapists and freelancers",
    sortOrder: 12,
  },
  {
    type: "EXPENSE",
    name: "Rent & Rates",
    nameEn: "Rent & Rates",
    namePt: "Aluguel e Taxas",
    hmrcCode: "RENT",
    hmrcLabel: "Rent, rates and property costs",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 65",
    isTaxDeductible: true,
    description: "Clinic rent, business rates, service charges",
    sortOrder: 13,
  },
  {
    type: "EXPENSE",
    name: "Repairs & Maintenance",
    nameEn: "Repairs & Maintenance",
    namePt: "Reparos e Manutenção",
    hmrcCode: "REPAIRS",
    hmrcLabel: "Repairs and maintenance",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 66",
    isTaxDeductible: true,
    description: "Building repairs, equipment maintenance, cleaning",
    sortOrder: 14,
  },
  {
    type: "EXPENSE",
    name: "Motor & Travel Expenses",
    nameEn: "Motor & Travel Expenses",
    namePt: "Despesas de Transporte e Viagem",
    hmrcCode: "MOTOR",
    hmrcLabel: "Motor expenses and travel",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 67",
    isTaxDeductible: true,
    description: "Vehicle costs, mileage, parking, public transport for business",
    sortOrder: 15,
  },
  {
    type: "EXPENSE",
    name: "Travel & Subsistence",
    nameEn: "Travel & Subsistence",
    namePt: "Viagens e Alimentação",
    hmrcCode: "TRAVEL",
    hmrcLabel: "Travel and subsistence",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 67",
    isTaxDeductible: true,
    description: "Business travel, accommodation, meals during travel",
    sortOrder: 16,
  },
  {
    type: "EXPENSE",
    name: "Professional Fees",
    nameEn: "Professional Fees",
    namePt: "Honorários Profissionais",
    hmrcCode: "PROFESSIONAL",
    hmrcLabel: "Professional fees and charges",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 68",
    isTaxDeductible: true,
    description: "Accountant, solicitor, consultant, professional body memberships (HCPC, CSP)",
    sortOrder: 17,
  },
  {
    type: "EXPENSE",
    name: "Insurance",
    nameEn: "Insurance",
    namePt: "Seguros",
    hmrcCode: "INSURANCE",
    hmrcLabel: "Insurance premiums",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 68",
    isTaxDeductible: true,
    description: "Professional indemnity, public liability, employer's liability, premises insurance",
    sortOrder: 18,
  },
  {
    type: "EXPENSE",
    name: "Advertising & Marketing",
    nameEn: "Advertising & Marketing",
    namePt: "Publicidade e Marketing",
    hmrcCode: "ADVERTISING",
    hmrcLabel: "Advertising and marketing",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 69",
    isTaxDeductible: true,
    description: "Google Ads, social media ads, printing, signage, website costs",
    sortOrder: 19,
  },
  {
    type: "EXPENSE",
    name: "Office & Admin Costs",
    nameEn: "Office & Admin Costs",
    namePt: "Custos de Escritório e Administrativos",
    hmrcCode: "OFFICE",
    hmrcLabel: "Office costs and supplies",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 70",
    isTaxDeductible: true,
    description: "Stationery, postage, printing, office supplies",
    sortOrder: 20,
  },
  {
    type: "EXPENSE",
    name: "Telephone & Internet",
    nameEn: "Telephone & Internet",
    namePt: "Telefone e Internet",
    hmrcCode: "TELECOMS",
    hmrcLabel: "Telephone and internet",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 70",
    isTaxDeductible: true,
    description: "Phone lines, mobile, broadband, VoIP services",
    sortOrder: 21,
  },
  {
    type: "EXPENSE",
    name: "Software & IT",
    nameEn: "Software & IT",
    namePt: "Software e TI",
    hmrcCode: "SOFTWARE",
    hmrcLabel: "Computer and software costs",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 70",
    isTaxDeductible: true,
    description: "SaaS subscriptions, hosting, domain names, IT support",
    sortOrder: 22,
  },
  {
    type: "EXPENSE",
    name: "Equipment & Tools",
    nameEn: "Equipment & Tools",
    namePt: "Equipamentos e Ferramentas",
    hmrcCode: "EQUIPMENT",
    hmrcLabel: "Equipment and small tools",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 70",
    isTaxDeductible: true,
    description: "Treatment equipment, physiotherapy tools, small items under £1,000",
    sortOrder: 23,
  },
  {
    type: "EXPENSE",
    name: "Utilities",
    nameEn: "Utilities",
    namePt: "Serviços Públicos",
    hmrcCode: "UTILITIES",
    hmrcLabel: "Light, heat and power",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 65",
    isTaxDeductible: true,
    description: "Electricity, gas, water for the clinic premises",
    sortOrder: 24,
  },
  {
    type: "EXPENSE",
    name: "Bank Charges & Interest",
    nameEn: "Bank Charges & Interest",
    namePt: "Tarifas Bancárias e Juros",
    hmrcCode: "BANK",
    hmrcLabel: "Bank charges and interest",
    companiesHouseSection: "PL/InterestPayable",
    ct600Box: "Box 71",
    isTaxDeductible: true,
    description: "Bank fees, card processing fees, Stripe fees, loan interest",
    sortOrder: 25,
  },
  {
    type: "EXPENSE",
    name: "Depreciation",
    nameEn: "Depreciation",
    namePt: "Depreciação",
    hmrcCode: "DEPRECIATION",
    hmrcLabel: "Depreciation of fixed assets",
    companiesHouseSection: "PL/Depreciation",
    ct600Box: "Box 66",
    isTaxDeductible: false,
    description: "Annual depreciation charge on capital equipment (not tax deductible — use capital allowances)",
    sortOrder: 26,
  },
  {
    type: "EXPENSE",
    name: "Training & CPD",
    nameEn: "Training & CPD",
    namePt: "Treinamento e Desenvolvimento Profissional",
    hmrcCode: "TRAINING",
    hmrcLabel: "Staff training costs",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 63",
    isTaxDeductible: true,
    description: "Courses, conferences, CPD hours, certifications",
    sortOrder: 27,
  },
  {
    type: "EXPENSE",
    name: "Clinical Supplies & Consumables",
    nameEn: "Clinical Supplies & Consumables",
    namePt: "Materiais Clínicos e Descartáveis",
    hmrcCode: "SUPPLIES",
    hmrcLabel: "Clinical supplies",
    companiesHouseSection: "PL/CostOfSales",
    ct600Box: "Box 146",
    isTaxDeductible: true,
    description: "Tapes, electrodes, creams, disposables, PPE, gowns",
    sortOrder: 28,
  },
  {
    type: "EXPENSE",
    name: "Corporation Tax",
    nameEn: "Corporation Tax",
    namePt: "Imposto Corporativo",
    hmrcCode: "CORP_TAX",
    hmrcLabel: "Corporation tax",
    companiesHouseSection: "PL/TaxOnProfit",
    ct600Box: "Box 86",
    isTaxDeductible: false,
    description: "Corporation tax payable to HMRC",
    sortOrder: 29,
  },
  {
    type: "EXPENSE",
    name: "VAT",
    nameEn: "VAT",
    namePt: "IVA",
    hmrcCode: "VAT",
    hmrcLabel: "Value Added Tax",
    companiesHouseSection: "BS/Creditors",
    ct600Box: "N/A",
    isTaxDeductible: false,
    description: "VAT payments (note: most healthcare services are VAT exempt)",
    sortOrder: 30,
  },
  {
    type: "EXPENSE",
    name: "Other Expenses",
    nameEn: "Other Expenses",
    namePt: "Outras Despesas",
    hmrcCode: "OTHER",
    hmrcLabel: "Other business expenses",
    companiesHouseSection: "PL/AdminExpenses",
    ct600Box: "Box 70",
    isTaxDeductible: true,
    description: "Miscellaneous expenses not covered by other categories",
    sortOrder: 99,
  },
];
