"use client";

import { useState } from "react";
import Link from "next/link";
import {
  ArrowLeft, ArrowRight, HeartPulse, CheckCircle2, ChevronDown,
  Clock, Shield, Target, Brain, Activity,
  Zap, Waves, RefreshCw, BarChart3, Layers,
  AlertTriangle, Users, FlaskConical, TrendingDown,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLocale } from "@/hooks/use-locale";

export default function ChronicPainPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const { locale } = useLocale();
  const isPt = locale === "pt-BR";
  const L = (en: string, pt: string) => isPt ? pt : en;

  const painScience = [
    {
      icon: Brain,
      color: "bg-violet-100 text-violet-700",
      badge: "bg-violet-500/15 text-violet-400 border-violet-500/20",
      en_label: "Pain Neuroscience",
      pt_label: "Neurociência da Dor",
      en_title: "Pain is a Brain Output — Not a Tissue Signal",
      pt_title: "A Dor é uma Saída do Cérebro — Não um Sinal Tecidual",
      en_desc: "The most important shift in pain science in the last 30 years is the recognition that pain is not simply a signal transmitted from damaged tissue to the brain. Pain is an output — a protective response generated by the brain when it perceives threat to the body, regardless of whether tissue damage is actually present. This is why you can have severe structural damage with minimal pain (asymptomatic rotator cuff tears, disc bulges in 50% of pain-free adults over 40), and why you can have severe, disabling pain with minimal or no structural pathology visible on imaging.",
      pt_desc: "A mudança mais importante na ciência da dor nos últimos 30 anos é o reconhecimento de que a dor não é simplesmente um sinal transmitido do tecido danificado para o cérebro. A dor é uma saída — uma resposta protetora gerada pelo cérebro quando percepciona ameaça ao corpo, independentemente de existir dano tecidual real. É por isso que é possível ter dano estrutural grave com dor mínima (rupturas assintomáticas do manguito rotador, protrusões discais em 50% dos adultos sem dor com mais de 40 anos), e é por isso que é possível ter dor grave e incapacitante com patologia estrutural mínima ou inexistente visível na imagem.",
    },
    {
      icon: AlertTriangle,
      color: "bg-amber-100 text-amber-700",
      badge: "bg-amber-500/15 text-amber-400 border-amber-500/20",
      en_label: "Central Sensitisation",
      pt_label: "Sensibilização Central",
      en_title: "When the Nervous System Becomes Hypersensitive",
      pt_title: "Quando o Sistema Nervoso se Torna Hipersensível",
      en_desc: "Central sensitisation (CS) is the process by which the central nervous system — the brain and spinal cord — undergoes neuroplastic changes that amplify pain signals from the periphery. After a period of sustained or repeated nociceptive input, the nervous system 'learns' pain: synaptic connections in the dorsal horn become potentiated (wind-up), descending inhibitory pathways are suppressed, and cortical representations of the painful area expand. The result: stimuli that were previously neutral (light touch, temperature, movement) become painful (allodynia); normal painful stimuli produce exaggerated responses (hyperalgesia). This is not psychological — it is measurable neurological change.",
      pt_desc: "A sensibilização central (SC) é o processo pelo qual o sistema nervoso central — o cérebro e a espinhal medula — sofre alterações neuroplásticas que amplificam os sinais de dor da periferia. Após um período de input nociceptivo sustentado ou repetido, o sistema nervoso 'aprende' a dor: as conexões sinápticas no corno dorsal tornam-se potenciadas (wind-up), as vias inibitórias descendentes são suprimidas e as representações corticais da área dolorosa expandem-se. O resultado: estímulos que anteriormente eram neutros (toque leve, temperatura, movimento) tornam-se dolorosos (alodinia); estímulos dolorosos normais produzem respostas exageradas (hiperalgesia). Isto não é psicológico — é uma alteração neurológica mensurável.",
    },
    {
      icon: Layers,
      color: "bg-rose-100 text-rose-700",
      badge: "bg-rose-500/15 text-rose-400 border-rose-500/20",
      en_label: "Pain Mechanisms",
      pt_label: "Mecanismos da Dor",
      en_title: "Three Distinct Chronic Pain Mechanisms",
      pt_title: "Três Mecanismos Distintos de Dor Crónica",
      en_desc: "Accurate treatment depends on identifying the dominant pain mechanism. Nociceptive pain: ongoing peripheral tissue damage drives the pain signal — inflammation, osteoarthritis, active tissue injury. Responds well to anti-inflammatory and loading interventions. Neuropathic pain: damage or disease of the somatosensory nervous system — nerve compression, diabetic neuropathy, post-herpetic neuralgia, radiculopathy. Characterised by burning, shooting, electric-shock quality and sensory changes. Nociplastic pain: pain arising from altered nociception without clear evidence of tissue damage or somatosensory system disease (fibromyalgia, widespread pain). Driven by central sensitisation and requires pain neuroscience education, graded exposure, and nervous system regulation strategies.",
      pt_desc: "O tratamento preciso depende de identificar o mecanismo de dor dominante. Dor nociceptiva: o dano tecidual periférico em curso impulsiona o sinal de dor — inflamação, osteoartrite, lesão tecidual activa. Responde bem a intervenções anti-inflamatórias e de carga. Dor neuropática: dano ou doença do sistema somatosensorial — compressão nervosa, neuropatia diabética, nevralgia pós-herpética, radiculopatia. Caracterizada por qualidade de queimação, pontada, choque eléctrico e alterações sensoriais. Dor nociplástica: dor resultante de nociceptividade alterada sem evidência clara de dano tecidual ou doença do sistema somatosensorial (fibromialgia, dor generalizada). Impulsionada por sensibilização central e requer educação em neurociência da dor, exposição graduada e estratégias de regulação do sistema nervoso.",
    },
    {
      icon: Users,
      color: "bg-blue-100 text-blue-700",
      badge: "bg-blue-500/15 text-blue-400 border-blue-500/20",
      en_label: "Biopsychosocial Model",
      pt_label: "Modelo Biopsicossocial",
      en_title: "Biology, Psychology, and Context All Drive Pain",
      pt_title: "Biologia, Psicologia e Contexto Impulsionam a Dor",
      en_desc: "Chronic pain is not purely biological — it is determined by the interaction of three domains. Biological: tissue damage level, inflammation, sensitisation, sleep quality, nutritional status, hormonal profile. Psychological: fear-avoidance beliefs, pain catastrophising, anxiety, depression, self-efficacy (confidence in ability to cope). Social: work demands, financial stress, relationship quality, social support, cultural beliefs about pain and recovery. Effective chronic pain treatment must address all three domains. Ignoring the psychological and social drivers — and treating only the tissue — explains why conventional treatment so frequently fails for chronic pain.",
      pt_desc: "A dor crónica não é puramente biológica — é determinada pela interação de três domínios. Biológico: nível de dano tecidual, inflamação, sensibilização, qualidade do sono, estado nutricional, perfil hormonal. Psicológico: crenças de evitação por medo, catastrofização da dor, ansiedade, depressão, auto-eficácia (confiança na capacidade de lidar). Social: exigências de trabalho, stress financeiro, qualidade das relações, suporte social, crenças culturais sobre dor e recuperação. O tratamento eficaz da dor crónica deve abordar os três domínios. Ignorar os drivers psicológicos e sociais — e tratar apenas o tecido — explica porque o tratamento convencional falha tão frequentemente na dor crónica.",
    },
  ];

  const conditions = [
    {
      cat: L("Spinal Pain", "Dor Espinhal"),
      color: "bg-violet-500/10 text-violet-400 border-violet-500/20",
      items: [
        L("Chronic low back pain — non-specific and structural", "Dor lombar crónica — não específica e estrutural"),
        L("Chronic neck pain — including whiplash", "Dor cervical crónica — incluindo whiplash"),
        L("Lumbar disc pathology with radiculopathy", "Patologia discal lombar com radiculopatia"),
        L("Cervical disc pathology with arm symptoms", "Patologia discal cervical com sintomas no braço"),
        L("Facet joint syndrome", "Síndrome da articulação facetária"),
        L("Sacroiliac joint dysfunction", "Disfunção da articulação sacroilíaca"),
      ],
    },
    {
      cat: L("Neuropathic Pain", "Dor Neuropática"),
      color: "bg-blue-500/10 text-blue-400 border-blue-500/20",
      items: [
        L("Peripheral neuropathy — diabetic, post-chemo", "Neuropatia periférica — diabética, pós-quimioterapia"),
        L("Post-herpetic neuralgia (shingles pain)", "Nevralgia pós-herpética (dor de zona)"),
        L("Complex regional pain syndrome (CRPS)", "Síndrome de dor regional complexa (SDRC)"),
        L("Phantom limb pain — post-amputation", "Dor fantasma — pós-amputação"),
        L("Thoracic outlet syndrome", "Síndrome do desfiladeiro torácico"),
        L("Carpal tunnel & nerve entrapment pain", "Dor do canal cárpico & compressão nervosa"),
      ],
    },
    {
      cat: L("Widespread & Nociplastic Pain", "Dor Generalizada & Nociplástica"),
      color: "bg-rose-500/10 text-rose-400 border-rose-500/20",
      items: [
        L("Fibromyalgia — widespread musculoskeletal pain", "Fibromialgia — dor musculoesquelética generalizada"),
        L("Myofascial pain syndrome — trigger points", "Síndrome de dor miofascial — pontos-gatilho"),
        L("Chronic pelvic pain", "Dor pélvica crónica"),
        L("Temporomandibular disorders (TMD)", "Distúrbios temporomandibulares (DTM)"),
        L("Persistent post-surgical pain", "Dor persistente pós-cirúrgica"),
        L("Central sensitisation — widespread hypersensitivity", "Sensibilização central — hipersensibilidade generalizada"),
      ],
    },
    {
      cat: L("Articular & Degenerative", "Articular & Degenerativa"),
      color: "bg-amber-500/10 text-amber-400 border-amber-500/20",
      items: [
        L("Osteoarthritis — knee, hip, shoulder, spine", "Osteoartrite — joelho, anca, ombro, coluna"),
        L("Rheumatoid arthritis flare management", "Gestão de crises de artrite reumatoide"),
        L("Ankylosing spondylitis — functional maintenance", "Espondilite anquilosante — manutenção funcional"),
        L("Psoriatic arthritis", "Artrite psoriásica"),
        L("Chronic bursitis", "Bursite crónica"),
        L("Chronic tendinopathy — non-responsive to standard care", "Tendinopatia crónica — não responsiva ao cuidado padrão"),
      ],
    },
  ];

  const treatmentApproach = [
    {
      icon: Brain, color: "bg-violet-100 text-violet-700",
      en_title: "Pain Neuroscience Education (PNE)",
      pt_title: "Educação em Neurociência da Dor (END)",
      en_desc: "Developed by Lorimer Moseley and David Butler, PNE is one of the most evidence-based interventions for chronic pain. Explaining pain neuroscience — how the nervous system becomes sensitised, why pain is not a reliable indicator of tissue damage, and what drives pain amplification — consistently reduces pain intensity, fear-avoidance, catastrophising, and disability in chronic pain populations. Understanding your pain biologically changes how threatening it feels — and that change in perceived threat directly reduces the brain's output of pain. We integrate PNE into every chronic pain programme from the first session.",
      pt_desc: "Desenvolvida por Lorimer Moseley e David Butler, a END é uma das intervenções mais baseadas em evidências para a dor crónica. Explicar a neurociência da dor — como o sistema nervoso se sensibiliza, por que a dor não é um indicador fiável de dano tecidual e o que impulsiona a amplificação da dor — reduz consistentemente a intensidade da dor, a evitação por medo, a catastrofização e a incapacidade em populações com dor crónica. Compreender a sua dor biologicamente altera o quão ameaçadora ela parece — e essa mudança na ameaça percebida reduz directamente a saída de dor do cérebro. Integramos a END em cada programa de dor crónica desde a primeira sessão.",
    },
    {
      icon: Activity, color: "bg-emerald-100 text-emerald-700",
      en_title: "Graded Activity & Exposure",
      pt_title: "Actividade Graduada & Exposição Graduada",
      en_desc: "Graded activity progressively increases physical activity levels using a time-contingent (rather than pain-contingent) approach — breaking the pain-avoidance cycle that perpetuates chronic pain. Graded exposure specifically targets feared movements and activities, systematically reducing movement-related fear through controlled, predictable exposure. Both approaches are derived from cognitive-behavioural science applied to pain and have strong evidence bases for reducing disability and improving function in fibromyalgia, chronic low back pain, and CRPS.",
      pt_desc: "A actividade graduada aumenta progressivamente os níveis de atividade física usando uma abordagem tempo-contingente (em vez de dor-contingente) — quebrando o ciclo dor-evitação que perpetua a dor crónica. A exposição graduada dirige-se especificamente a movimentos e atividades temidos, reduzindo sistematicamente o medo relacionado com o movimento através de exposição controlada e previsível. Ambas as abordagens derivam da ciência cognitivo-comportamental aplicada à dor e têm bases de evidências sólidas para reduzir a incapacidade e melhorar a função na fibromialgia, dor lombar crónica e SDRC.",
    },
    {
      icon: Zap, color: "bg-amber-100 text-amber-700",
      en_title: "Electrotherapy for Pain Modulation",
      pt_title: "Eletroterapia para Modulação da Dor",
      en_desc: "Gate Control Theory (Melzack & Wall, 1965) provides the neurophysiological basis for using TENS (transcutaneous electrical nerve stimulation) to modulate chronic pain. High-frequency TENS (80–150 Hz) activates large-diameter Aβ mechanoreceptor fibres that inhibit nociceptive transmission in the dorsal horn — 'closing the gate' to pain signals. Low-frequency TENS (2–10 Hz) triggers endogenous opioid release at spinal and supraspinal levels, providing longer-duration analgesia. Interferential therapy (IFT) penetrates more deeply to modulate nociception in deeper structures. For central sensitisation, electrotherapy is combined with PNE and graded activity for a multi-mechanistic approach.",
      pt_desc: "A Teoria do Controlo do Portal (Melzack & Wall, 1965) fornece a base neurofisiológica para usar TENS (estimulação elétrica nervosa transcutânea) para modular a dor crónica. O TENS de alta frequência (80–150 Hz) activa fibras mecanorreceptoras Aβ de grande diâmetro que inibem a transmissão nociceptiva no corno dorsal — 'fechando o portal' aos sinais de dor. O TENS de baixa frequência (2–10 Hz) desencadeia libertação de opioides endógenos a nível espinhal e supraespinhal, proporcionando analgesia de duração mais longa. A terapia interferencial (IFT) penetra mais profundamente para modular a nociceptividade em estruturas mais profundas. Para sensibilização central, a eletroterapia é combinada com END e actividade graduada para uma abordagem multi-mecanística.",
    },
    {
      icon: FlaskConical, color: "bg-cyan-100 text-cyan-700",
      en_title: "Exercise as Analgesic",
      pt_title: "Exercício como Analgésico",
      en_desc: "Exercise-induced hypoalgesia (EIH) is the reduction in pain sensitivity that occurs during and after physical activity. The mechanisms include: release of endorphins and endocannabinoids (the body's endogenous pain-modulating chemicals), activation of descending inhibitory pain pathways from the periaqueductal grey (PAG), reduction in pro-inflammatory cytokines (TNF-α, IL-6, IL-1β), and normalisation of cortisol and adrenaline stress hormones. For chronic pain patients, exercise is prescribed at low to moderate intensity and gradually progressed — always starting below the threshold that provokes excessive symptom flare, and building tolerance through consistent, repeated exposure.",
      pt_desc: "A hipoalgesia induzida pelo exercício (HIE) é a redução na sensibilidade à dor que ocorre durante e após a atividade física. Os mecanismos incluem: libertação de endorfinas e endocanabinoides (os químicos endógenos de modulação da dor do corpo), activação das vias de dor inibitórias descendentes a partir da substância cinzenta periaquedutal (SCP), redução de citocinas pró-inflamatórias (TNF-α, IL-6, IL-1β) e normalização das hormonas de stress cortisol e adrenalina. Para pacientes com dor crónica, o exercício é prescrito a intensidade baixa a moderada e progressivamente aumentado — sempre começando abaixo do limiar que provoca agravamento excessivo dos sintomas, e construindo tolerância através de exposição consistente e repetida.",
    },
    {
      icon: RefreshCw, color: "bg-rose-100 text-rose-700",
      en_title: "MLS Laser — Photobiomodulation for Pain",
      pt_title: "Laser MLS — Fotobiomodulação para Dor",
      en_desc: "The 905 nm pulsed wavelength of the MLS® Mphi 75 has documented analgesic effects through several mechanisms: suppression of nociceptive fibre (C and Aδ) activity, reduction of pro-inflammatory mediators (PGE2, bradykinin, substance P) at peripheral pain sites, promotion of endogenous endorphin synthesis, and modulation of mitochondrial function in sensitised peripheral neurons. For chronic pain conditions with a peripheral component — osteoarthritis, tendinopathy, neuropathic pain, trigger points — MLS laser combined with exercise and PNE provides multi-mechanistic pain modulation that is completely non-pharmacological.",
      pt_desc: "O comprimento de onda pulsado de 905 nm do MLS® Mphi 75 tem efeitos analgésicos documentados através de vários mecanismos: supressão da actividade das fibras nociceptivas (C e Aδ), redução de mediadores pró-inflamatórios (PGE2, bradicinina, substância P) em locais de dor periférica, promoção da síntese de endorfinas endógenas e modulação da função mitocondrial em neurónios periféricos sensibilizados. Para condições de dor crónica com componente periférica — osteoartrite, tendinopatia, dor neuropática, pontos-gatilho — o laser MLS combinado com exercício e END fornece modulação da dor multi-mecanística completamente não farmacológica.",
    },
    {
      icon: TrendingDown, color: "bg-indigo-100 text-indigo-700",
      en_title: "Sleep, Stress & Lifestyle Regulation",
      pt_title: "Regulação do Sono, Stress & Estilo de Vida",
      en_desc: "Poor sleep is both a consequence and a driver of chronic pain — a bidirectional relationship that creates a self-perpetuating cycle. Sleep deprivation increases central sensitisation, lowers pain thresholds, and reduces the effectiveness of descending inhibitory pain pathways. Similarly, psychological stress activates the HPA axis and sympathetic nervous system, elevating cortisol and pro-inflammatory cytokines that maintain peripheral sensitisation. Our chronic pain programmes include sleep hygiene guidance, stress regulation strategies, and — where appropriate — integration with our biohacking and HRV monitoring protocols to address these systemic drivers.",
      pt_desc: "O sono deficiente é simultaneamente uma consequência e um driver da dor crónica — uma relação bidirecional que cria um ciclo auto-perpetuante. A privação de sono aumenta a sensibilização central, baixa os limiares de dor e reduz a eficácia das vias de dor inibitórias descendentes. Da mesma forma, o stress psicológico activa o eixo HPA e o sistema nervoso simpático, elevando o cortisol e as citocinas pró-inflamatórias que mantêm a sensibilização periférica. Os nossos programas de dor crónica incluem orientação de higiene do sono, estratégias de regulação do stress e — quando apropriado — integração com os nossos protocolos de biohacking e monitorização de VFC para abordar estes drivers sistémicos.",
    },
  ];

  const faqs = [
    {
      en_q: "Is chronic pain 'all in my head'?",
      pt_q: "A dor crónica é 'apenas na minha cabeça'?",
      en_a: "No — and this is the most damaging misconception in chronic pain. Chronic pain involves real, measurable neurological changes in the central nervous system — increased synaptic sensitivity in the dorsal horn, altered cortical representations, suppressed descending inhibitory pathways. These are not imagined — they are documented on functional MRI, in cerebrospinal fluid inflammatory markers, and in quantitative sensory testing. The critical insight is that these changes can occur without proportionate tissue damage: the nervous system becomes hypersensitive and amplifies pain signals that would not normally produce pain. The fact that emotional states, sleep, stress, and beliefs about pain influence its intensity does not make it psychological — it reflects the reality that all these factors modulate how the brain processes threat, and pain is the brain's threat response.",
      pt_a: "Não — e esta é a ideia errada mais prejudicial na dor crónica. A dor crónica envolve alterações neurológicas reais e mensuráveis no sistema nervoso central — sensibilidade sináptica aumentada no corno dorsal, representações corticais alteradas, vias inibitórias descendentes suprimidas. Estas não são imaginárias — são documentadas em RMf funcional, em marcadores inflamatórios do líquido cefalorraquidiano e em testes sensoriais quantitativos. O insight crítico é que estas alterações podem ocorrer sem dano tecidual proporcional: o sistema nervoso torna-se hipersensível e amplifica sinais de dor que normalmente não produziriam dor. O facto de estados emocionais, sono, stress e crenças sobre a dor influenciarem a sua intensidade não a torna psicológica — reflecte a realidade de que todos estes factores modulam a forma como o cérebro processa a ameaça, e a dor é a resposta de ameaça do cérebro.",
    },
    {
      en_q: "Why does my pain keep spreading to new areas?",
      pt_q: "Porque é que a minha dor continua a espalhar-se para novas áreas?",
      en_a: "Pain spreading beyond its original location — and to areas with no structural injury — is a hallmark sign of central sensitisation. As the nervous system becomes sensitised, the area of cortical representation of the painful body part expands (smearing), and the descending inhibitory pathways that normally suppress pain signals from other areas become less effective. Additionally, protective motor changes — altered movement patterns, guarding, and avoidance — create secondary musculoskeletal loading problems in adjacent structures. Understanding that pain spread is a neurological process rather than evidence of progressive tissue damage spreading through the body is clinically important: it changes the treatment target from the new pain location back to the sensitised nervous system.",
      pt_a: "A dor a espalhar-se além da sua localização original — e para áreas sem lesão estrutural — é um sinal característico de sensibilização central. À medida que o sistema nervoso se sensibiliza, a área de representação cortical da parte do corpo dolorosa expande-se (smearing), e as vias inibitórias descendentes que normalmente suprimem os sinais de dor de outras áreas tornam-se menos eficazes. Adicionalmente, as alterações motoras protetoras — padrões de movimento alterados, guarda e evitação — criam problemas secundários de carga musculoesquelética em estruturas adjacentes. Compreender que a propagação da dor é um processo neurológico em vez de evidência de dano tecidual progressivo a espalhar-se pelo corpo é clinicamente importante: muda o alvo do tratamento da nova localização da dor de volta ao sistema nervoso sensibilizado.",
    },
    {
      en_q: "Can chronic pain be cured, or only managed?",
      pt_q: "A dor crónica pode ser curada, ou apenas gerida?",
      en_a: "For many patients — particularly those in the early-to-moderate stages of central sensitisation — significant, sustained reduction in pain to levels that no longer limit function is achievable. This is not 'management' in the sense of passive coping — it is active neurobiological recovery. The nervous system can and does undergo reverse neuroplasticity when the conditions that maintain sensitisation are addressed: reducing peripheral nociceptive input (treating the original injury), down-regulating the sensitised nervous system through pain neuroscience education and graded exposure, improving sleep, regulating stress, and building physical resilience through exercise. For patients with more established central sensitisation or structural conditions like advanced osteoarthritis, complete resolution may not be achievable — but substantial improvements in pain intensity, function, and quality of life consistently are.",
      pt_a: "Para muitos pacientes — particularmente aqueles nos estágios iniciais a moderados de sensibilização central — uma redução significativa e sustentada da dor para níveis que já não limitam a função é alcançável. Isto não é 'gestão' no sentido de coping passivo — é recuperação neurobiológica activa. O sistema nervoso pode e sofre neuroplasticidade reversa quando as condições que mantêm a sensibilização são abordadas: reduzir o input nociceptivo periférico (tratar a lesão original), regular negativamente o sistema nervoso sensibilizado através de educação em neurociência da dor e exposição graduada, melhorar o sono, regular o stress e construir resiliência física através do exercício. Para pacientes com sensibilização central mais estabelecida ou condições estruturais como osteoartrite avançada, a resolução completa pode não ser alcançável — mas melhorias substanciais na intensidade da dor, função e qualidade de vida consistentemente são.",
    },
    {
      en_q: "My MRI / scan looks normal but I have severe pain — how is this possible?",
      pt_q: "A minha RM / exame está normal, mas tenho dor grave — como é isto possível?",
      en_a: "This is one of the most common presentations in chronic pain and one of the most destabilising for patients — being told your scan is normal when you have real, significant pain. The answer lies in understanding what imaging measures and what it does not. MRI and CT scan structural tissue — bones, discs, cartilage, soft tissues. They do not and cannot measure the state of the nervous system: the degree of central sensitisation, the sensitivity of nociceptive fibres, the balance of descending inhibitory versus facilitatory pathways, or the functional changes in the dorsal horn. A normal scan does not mean normal pain processing — it means the cause of your pain is in the nervous system rather than visible structural damage. This makes it treatable by approaches that target the nervous system: pain neuroscience education, graded exposure, electrotherapy for sensory re-normalisation, and exercise.",
      pt_a: "Esta é uma das apresentações mais comuns na dor crónica e uma das mais desestabilizadoras para os pacientes — ser-lhes dito que o exame está normal quando têm dor real e significativa. A resposta reside em compreender o que a imagem mede e o que não mede. A RM e a TC escaneiam o tecido estrutural — ossos, discos, cartilagem, tecidos moles. Não medem e não podem medir o estado do sistema nervoso: o grau de sensibilização central, a sensibilidade das fibras nociceptivas, o equilíbrio das vias inibitórias descendentes versus facilitatórias, ou as alterações funcionais no corno dorsal. Um exame normal não significa processamento normal da dor — significa que a causa da sua dor está no sistema nervoso em vez de no dano estrutural visível. Isto torna-a tratável por abordagens que visam o sistema nervoso: educação em neurociência da dor, exposição graduada, eletroterapia para renormalização sensorial e exercício.",
    },
    {
      en_q: "Can exercise make chronic pain worse?",
      pt_q: "O exercício pode piorar a dor crónica?",
      en_a: "The wrong exercise — too much, too fast, with too little recovery — can temporarily increase symptoms in sensitised patients, particularly in the early stages of rehabilitation. This is one of the reasons why unsupervised exercise programmes frequently fail for chronic pain: patients either avoid exercise because of pain fear, or they overdo it and experience a flare that reinforces avoidance. Graded activity — starting significantly below the symptomatic threshold and increasing incrementally on a time-contingent basis — reliably produces progressive improvements without sustained flares. Research consistently shows that regular, appropriately dosed aerobic and resistance exercise reduces central sensitisation, improves descending inhibition, and reduces chronic pain scores. Pain during exercise does not mean harm — understanding this distinction is critical for recovery.",
      pt_a: "O exercício errado — demasiado, demasiado rápido, com recuperação insuficiente — pode temporariamente aumentar os sintomas em pacientes sensibilizados, particularmente nas fases iniciais da reabilitação. Esta é uma das razões pelas quais os programas de exercício não supervisionados frequentemente falham na dor crónica: os pacientes ou evitam o exercício por medo da dor, ou exageram e experimentam um agravamento que reforça a evitação. A actividade graduada — começando significativamente abaixo do limiar sintomático e aumentando incrementalmente numa base tempo-contingente — produz de forma fiável melhorias progressivas sem agravamentos sustentados. A investigação mostra consistentemente que o exercício aeróbico e de resistência regular e apropriadamente doseado reduz a sensibilização central, melhora a inibição descendente e reduz as pontuações de dor crónica. A dor durante o exercício não significa dano — compreender esta distinção é crítico para a recuperação.",
    },
    {
      en_q: "Why do anti-inflammatory medications often not work well for chronic pain?",
      pt_q: "Porque é que os medicamentos anti-inflamatórios frequentemente não funcionam bem para a dor crónica?",
      en_a: "NSAIDs and corticosteroids work by reducing peripheral inflammatory mediators — prostaglandins, cytokines, and other chemicals produced at the site of tissue damage or inflammation. This is effective for acute inflammation and for pain that is predominantly driven by ongoing peripheral nociception. Chronic pain, however, is increasingly driven by central nervous system changes — sensitisation, altered descending modulation, cortical reorganisation — that are not responsive to peripheral anti-inflammatory drugs. No NSAID reduces dorsal horn sensitisation, normalises cortical pain maps, or restores descending inhibitory pathway function. This is why the majority of patients with established chronic pain report only partial, inconsistent, or temporary relief from anti-inflammatory medication — and why approaches targeting the nervous system (PNE, graded activity, electrotherapy, exercise) produce more durable results.",
      pt_a: "Os AINEs e os corticosteroides funcionam reduzindo os mediadores inflamatórios periféricos — prostaglandinas, citocinas e outros químicos produzidos no local do dano tecidual ou inflamação. Isto é eficaz para a inflamação aguda e para a dor que é predominantemente impulsionada pela nociceptividade periférica em curso. A dor crónica, no entanto, é crescentemente impulsionada por alterações do sistema nervoso central — sensibilização, modulação descendente alterada, reorganização cortical — que não são responsivas a medicamentos anti-inflamatórios periféricos. Nenhum AINE reduz a sensibilização do corno dorsal, normaliza os mapas corticais de dor ou restaura a função da via inibitória descendente. É por isso que a maioria dos pacientes com dor crónica estabelecida relata apenas alívio parcial, inconsistente ou temporário com medicação anti-inflamatória — e porque as abordagens que visam o sistema nervoso (END, actividade graduada, eletroterapia, exercício) produzem resultados mais duradouros.",
    },
  ];

  const whoFor = [
    L("Chronic back & neck pain", "Dor crónica lombar & cervical"),
    L("Fibromyalgia", "Fibromialgia"),
    L("Osteoarthritis", "Osteoartrite"),
    L("Neuropathic pain", "Dor neuropática"),
    L("CRPS", "SDRC"),
    L("Post-surgical persistent pain", "Dor pós-cirúrgica persistente"),
    L("Pain not responding to medication", "Dor não responsiva à medicação"),
    L("Myofascial & trigger point pain", "Dor miofascial & pontos-gatilho"),
    L("Widespread pain & hypersensitivity", "Dor generalizada & hipersensibilidade"),
    L("Pain with fear of movement", "Dor com medo de movimento"),
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Breadcrumb */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <Link href="/#services" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-primary transition-colors">
          <ArrowLeft className="h-4 w-4" />
          {L("All Services", "Todos os Serviços")}
        </Link>
      </div>

      {/* Hero */}
      <section className="relative py-12 sm:py-16 lg:py-20 overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-rose-500/[0.06] to-transparent" />
          <div className="absolute bottom-0 left-0 w-1/3 h-2/3 bg-gradient-to-tr from-violet-500/[0.04] to-transparent" />
        </div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-start gap-5 mb-6">
            <div className="w-16 h-16 rounded-2xl bg-rose-500/15 text-rose-400 flex items-center justify-center shrink-0 shadow-lg shadow-rose-500/10">
              <HeartPulse className="h-8 w-8" />
            </div>
            <div>
              <span className="inline-block px-3 py-1 rounded-full bg-rose-500/15 text-rose-400 text-xs font-semibold uppercase tracking-wider mb-3">
                {L("Chronic Pain Management", "Gestão da Dor Crónica")}
              </span>
              <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-foreground leading-tight">
                {L("Treat the Nervous System.", "Tratar o Sistema Nervoso.")}
                <span className="block text-transparent bg-clip-text bg-gradient-to-r from-rose-400 to-violet-500">
                  {L("Not Just the Pain Location.", "Não Apenas a Localização da Dor.")}
                </span>
              </h1>
            </div>
          </div>
          <p className="text-base sm:text-lg text-muted-foreground leading-relaxed max-w-3xl mb-6">
            {L(
              "Chronic pain is not a tissue problem — it is a nervous system problem. Modern pain neuroscience has fundamentally changed how we understand and treat pain that persists beyond tissue healing. Our approach combines pain education, graded movement, electrotherapy, laser, and lifestyle regulation to address the biological, psychological, and social drivers of your pain.",
              "A dor crónica não é um problema tecidual — é um problema do sistema nervoso. A neurociência moderna da dor mudou fundamentalmente a forma como compreendemos e tratamos a dor que persiste além da cicatrização tecidual. A nossa abordagem combina educação em dor, movimento graduado, eletroterapia, laser e regulação do estilo de vida para abordar os drivers biológicos, psicológicos e sociais da sua dor."
            )}
          </p>
          <div className="flex flex-wrap gap-3 mb-8">
            {[
              { en: "Pain Neuroscience Education", pt: "Educação em Neurociência" },
              { en: "Central Sensitisation", pt: "Sensibilização Central" },
              { en: "Graded Exposure", pt: "Exposição Graduada" },
              { en: "Non-Pharmacological", pt: "Não Farmacológico" },
            ].map((tag, i) => (
              <span key={i} className="px-3 py-1.5 rounded-full bg-muted/60 border border-border text-xs font-medium text-foreground">
                {isPt ? tag.pt : tag.en}
              </span>
            ))}
          </div>
          <div className="flex flex-col sm:flex-row gap-3">
            <Link href="/signup">
              <Button size="lg" className="gap-2 bg-gradient-to-r from-rose-500 to-violet-600 hover:from-rose-600 hover:to-violet-700 text-white shadow-lg shadow-rose-500/20">
                {L("Book Assessment", "Marcar Avaliação")} <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <Link href="/#services">
              <Button size="lg" variant="outline">{L("View All Services", "Ver Todos os Serviços")}</Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Pain Science */}
      <section className="py-14 sm:py-20 bg-card/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-10">
            <span className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold uppercase tracking-wider mb-3">
              {L("The Science of Chronic Pain", "A Ciência da Dor Crónica")}
            </span>
            <h2 className="text-2xl sm:text-3xl font-bold text-foreground">
              {L("What Modern Pain Science Has Changed", "O Que a Ciência Moderna da Dor Mudou")}
            </h2>
            <p className="mt-2 text-muted-foreground max-w-2xl">
              {L(
                "Understanding why chronic pain persists is the first step to treating it effectively. The science here is not optional — it is the foundation of the treatment.",
                "Compreender porque a dor crónica persiste é o primeiro passo para a tratar eficazmente. A ciência aqui não é opcional — é o alicerce do tratamento."
              )}
            </p>
          </div>
          <div className="grid sm:grid-cols-2 gap-5">
            {painScience.map((p, i) => {
              const PIcon = p.icon;
              return (
                <Card key={i} className="border border-border bg-card">
                  <CardContent className="p-6 sm:p-8">
                    <div className="flex items-center gap-3 mb-4">
                      <div className={`w-11 h-11 rounded-xl ${p.color} flex items-center justify-center shrink-0`}>
                        <PIcon className="h-5 w-5" />
                      </div>
                      <span className={`px-2.5 py-1 rounded-full border text-xs font-semibold ${p.badge}`}>
                        {isPt ? p.pt_label : p.en_label}
                      </span>
                    </div>
                    <h3 className="font-bold text-foreground mb-3">{isPt ? p.pt_title : p.en_title}</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">{isPt ? p.pt_desc : p.en_desc}</p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* Conditions */}
      <section className="py-14 sm:py-20 bg-background">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-10">
            <span className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold uppercase tracking-wider mb-3">
              {L("Conditions Treated", "Condições Tratadas")}
            </span>
            <h2 className="text-2xl sm:text-3xl font-bold text-foreground">
              {L("Clinical Applications", "Aplicações Clínicas")}
            </h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {conditions.map((c, i) => (
              <div key={i} className={`rounded-xl border ${c.color} p-5`}>
                <h3 className="font-bold text-sm uppercase tracking-wider mb-3 opacity-90">{c.cat}</h3>
                <ul className="space-y-2">
                  {c.items.map((item, j) => (
                    <li key={j} className="flex items-start gap-2 text-xs text-foreground">
                      <CheckCircle2 className="h-3.5 w-3.5 text-rose-400 shrink-0 mt-0.5" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Treatment Approach */}
      <section className="py-14 sm:py-20 bg-card/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-10">
            <span className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold uppercase tracking-wider mb-3">
              {L("Treatment Approach", "Abordagem de Tratamento")}
            </span>
            <h2 className="text-2xl sm:text-3xl font-bold text-foreground">
              {L("Six Pillars of Chronic Pain Treatment", "Seis Pilares do Tratamento da Dor Crónica")}
            </h2>
            <p className="mt-2 text-muted-foreground max-w-2xl">
              {L(
                "Chronic pain requires a multi-mechanistic approach. No single modality addresses all drivers of persistent pain — effective treatment combines tools that target the nervous system from multiple angles simultaneously.",
                "A dor crónica requer uma abordagem multi-mecanística. Nenhuma modalidade única aborda todos os drivers da dor persistente — o tratamento eficaz combina ferramentas que visam o sistema nervoso de múltiplos ângulos simultaneamente."
              )}
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {treatmentApproach.map((t, i) => {
              const TIcon = t.icon;
              return (
                <div key={i} className="p-6 rounded-xl bg-background border border-border">
                  <div className={`w-11 h-11 rounded-xl ${t.color} flex items-center justify-center mb-4`}>
                    <TIcon className="h-5 w-5" />
                  </div>
                  <h3 className="font-bold text-foreground mb-3">{isPt ? t.pt_title : t.en_title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{isPt ? t.pt_desc : t.en_desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Who For + Session Info */}
      <section className="py-14 sm:py-20 bg-background">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-start">
            <div>
              <span className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold uppercase tracking-wider mb-3">
                {L("Who Is It For?", "Para Quem É?")}
              </span>
              <h2 className="text-2xl sm:text-3xl font-bold text-foreground mb-4">
                {L("For patients where standard treatment has not worked", "Para pacientes onde o tratamento padrão não funcionou")}
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-6">
                {L(
                  "Our chronic pain service is specifically designed for patients who have seen multiple providers, tried multiple treatments, and still have persistent pain limiting their daily life. You are not a difficult case — your nervous system needs a different approach.",
                  "O nosso serviço de dor crónica é especificamente concebido para pacientes que consultaram múltiplos profissionais, experimentaram múltiplos tratamentos e ainda têm dor persistente a limitar a sua vida diária. Não é um caso difícil — o seu sistema nervoso precisa de uma abordagem diferente."
                )}
              </p>
              <div className="flex flex-wrap gap-2">
                {whoFor.map((w, i) => (
                  <span key={i} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-full bg-muted/60 text-sm font-medium text-foreground border border-border">
                    <CheckCircle2 className="h-3.5 w-3.5 text-rose-400 shrink-0" />
                    {w}
                  </span>
                ))}
              </div>
            </div>
            <div>
              <span className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold uppercase tracking-wider mb-3">
                {L("Session Information", "Informações da Sessão")}
              </span>
              <h2 className="text-2xl sm:text-3xl font-bold text-foreground mb-4">
                {L("What to Expect", "O Que Esperar")}
              </h2>
              <div className="space-y-3">
                {[
                  { icon: Clock, label: L("Initial Assessment", "Avaliação Inicial"), value: L("75–90 minutes — full pain history, mechanism assessment, PNE introduction", "75–90 minutos — historial completo de dor, avaliação de mecanismo, introdução END") },
                  { icon: Activity, label: L("Follow-up Sessions", "Sessões de Seguimento"), value: L("45–60 minutes — combined treatment, PNE, graded activity progression", "45–60 minutos — tratamento combinado, END, progressão de actividade graduada") },
                  { icon: Target, label: L("Programme Length", "Duração do Programa"), value: L("Typically 8–16 weeks with reassessment at 4 weeks", "Tipicamente 8–16 semanas com reavaliação às 4 semanas") },
                  { icon: Brain, label: L("Home Programme", "Programa Domiciliar"), value: L("Education materials + graded activity plan via patient portal", "Materiais de educação + plano de actividade graduada via portal do paciente") },
                  { icon: Shield, label: L("Goals", "Objetivos"), value: L("Reduce pain intensity, improve function, restore confidence in movement", "Reduzir intensidade da dor, melhorar função, restaurar confiança no movimento") },
                ].map((item, i) => {
                  const IIcon = item.icon;
                  return (
                    <div key={i} className="flex items-start gap-3 p-3 rounded-xl bg-card border border-border">
                      <div className="w-9 h-9 rounded-lg bg-rose-500/15 text-rose-400 flex items-center justify-center shrink-0">
                        <IIcon className="h-4 w-4" />
                      </div>
                      <div>
                        <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-0.5">{item.label}</p>
                        <p className="text-sm text-foreground">{item.value}</p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-14 sm:py-20 bg-card/50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-10">
            <span className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold uppercase tracking-wider mb-3">
              {L("Common Questions", "Perguntas Frequentes")}
            </span>
            <h2 className="text-2xl sm:text-3xl font-bold text-foreground">
              {L("Frequently Asked Questions", "Perguntas Frequentes")}
            </h2>
          </div>
          <div className="space-y-3">
            {faqs.map((f, i) => (
              <div key={i} className="border border-border rounded-xl overflow-hidden">
                <button
                  className="w-full flex items-center justify-between p-5 text-left hover:bg-muted/30 transition-colors"
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                >
                  <span className="font-semibold text-foreground pr-4">{isPt ? f.pt_q : f.en_q}</span>
                  <ChevronDown className={`h-5 w-5 text-muted-foreground shrink-0 transition-transform ${openFaq === i ? "rotate-180" : ""}`} />
                </button>
                {openFaq === i && (
                  <div className="px-5 pb-5 text-muted-foreground leading-relaxed text-sm">
                    {isPt ? f.pt_a : f.en_a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-14 sm:py-20 bg-gradient-to-r from-rose-500/10 via-violet-500/5 to-background">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-2xl sm:text-3xl font-bold text-foreground mb-4">
            {L("Persistent pain has a reason. And a solution.", "A dor persistente tem uma razão. E uma solução.")}
          </h2>
          <p className="text-muted-foreground mb-8 leading-relaxed">
            {L(
              "Book your chronic pain assessment and let us identify the mechanism driving your pain — and design a programme that addresses it at the source.",
              "Marque a sua avaliação de dor crónica e deixe-nos identificar o mecanismo que impulsiona a sua dor — e conceber um programa que a aborde na origem."
            )}
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link href="/signup">
              <Button size="lg" className="gap-2 bg-gradient-to-r from-rose-500 to-violet-600 hover:from-rose-600 hover:to-violet-700 text-white shadow-lg shadow-rose-500/20">
                {L("Book Assessment", "Marcar Avaliação")} <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <Link href="/#services">
              <Button size="lg" variant="outline">{L("View All Services", "Ver Todos os Serviços")}</Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
