import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth-options'
import { claudeGenerate } from '@/lib/claude'
import { BPR_SYSTEM_CONTEXT } from '@/lib/marketing-prompts'

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session || !['ADMIN', 'SUPERADMIN'].includes((session.user as any)?.role)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { niche = 'physiotherapy', platform = 'instagram', language = 'en' } = await req.json()

    const langNote = language === 'pt' ? 'Provide titles and captions in Portuguese (pt-BR).' : 'Provide titles and captions in English.'

    const prompt = `You are a viral content strategist for BPR (Bruno Physical Rehabilitation), a premium physio clinic in Richmond/Ipswich, UK.

Topic/Niche: ${niche}
Platform: Instagram
${langNote}

BPR has these connected assets to promote:
- Website: bpr.rehab (booking, services, blog)
- Marketplace: digital health guides/PDFs for sale
- SEO Blog Articles (educational long-form content)
- Services: MLS Laser, Custom Insoles, Biomechanical Assessment, Thermography, Sports Recovery, Shockwave, Exercise Therapy
- Founder story: Bruno, ex-professional footballer (Brazil/Germany/Sweden), 3 knee surgeries

Based on the topic "${niche}", identify 6 high-performing viral content formats on Instagram in 2024-2025.

For each idea provide:
1. FORMAT (e.g. "3 Signs You Have X", "Myth vs Truth", "Before/After", "Day in the Life", etc.)
2. CONTENT TYPE: IMAGE, REEL, or CAROUSEL (choose the best fit)
3. Why it goes viral (psychology)
4. BPR-specific recreation idea
5. The hook (exact first line to stop the scroll)
6. Full caption ready to post
7. 15-20 hashtags
8. Visual direction (what to film/show)
9. BPR asset connection: which BPR asset to connect (e.g. "Link to PDF guide on knee pain in bio", "Book assessment at bpr.rehab", "Mention marketplace guide", "Link to blog article")
10. Viral score 1-10
11. Best day/time to post (e.g. "Tuesday 7am" or "Saturday 9am")

Return as JSON array:
[
  {
    "id": 1,
    "format": "Format name",
    "viral_reason": "Why this works",
    "viral_score": 9,
    "content_type": "REEL",
    "bpr_adaptation": "Specific BPR idea",
    "hook": "Exact opening line",
    "caption": "Full caption",
    "hashtags": ["tag1"],
    "visual_direction": "What to film",
    "bpr_connection": "Which asset to link/mention",
    "best_time": "Tuesday 7am",
    "trending_reference": "Why trending now"
  }
]`

    const raw = await claudeGenerate(
      [{ role: 'user', content: prompt }],
      { temperature: 0.9, maxTokens: 4000, systemPrompt: BPR_SYSTEM_CONTEXT }
    )

    let ideas: any[]
    try {
      const jsonMatch = raw.match(/\[[\s\S]*\]/)
      if (!jsonMatch) throw new Error('No JSON array')
      ideas = JSON.parse(jsonMatch[0])
    } catch {
      ideas = [{
        id: 1,
        format: 'Viral Content Ideas',
        viral_reason: 'Generated by AI',
        viral_score: 8,
        content_type: 'IMAGE',
        bpr_adaptation: raw.slice(0, 200),
        hook: 'Stop scrolling if you have knee pain...',
        caption: raw.slice(0, 300),
        hashtags: ['#physiotherapy', '#BPR', '#rehabilitation'],
        visual_direction: 'Professional clinic setting',
        trending_reference: 'Health & wellness content',
      }]
    }

    return NextResponse.json({ success: true, ideas })
  } catch (error: any) {
    console.error('Viral scout error:', error)
    return NextResponse.json({ error: error?.message || 'Failed' }, { status: 500 })
  }
}
