import { PrismaClient } from "@prisma/client";
import { generateImageSmart } from "../lib/ai-provider";
import { uploadToInterServer, isInterServerConfigured } from "../lib/interserver-storage";

const prisma = new PrismaClient();

async function generateImageForArticle(article: any) {
  try {
    console.log(`\n🎨 Gerando imagem para: "${article.title}"`);
    
    const prompt = `Professional article cover image for physiotherapy clinic blog: ${article.title}. Medical, healthcare, modern, clean, professional photography style.`;
    
    console.log(`   Aguardando geração com IA (60-120s)...`);
    
    const imageUrls = await generateImageSmart(prompt, { numImages: 1 });
    
    if (!imageUrls || imageUrls.length === 0) {
      throw new Error('No image generated by AI');
    }

    const dataUrl = imageUrls[0];
    console.log(`   ✅ Imagem gerada!`);

    let finalImageUrl = dataUrl;
    
    if (isInterServerConfigured() && dataUrl.startsWith('data:')) {
      try {
        console.log(`   📤 Upload para InterServer...`);
        
        const base64Data = dataUrl.split(',')[1];
        const buffer = Buffer.from(base64Data, 'base64');
        const filename = `article-${article.slug}-${Date.now()}.png`;
        
        finalImageUrl = await uploadToInterServer(buffer, filename);
        console.log(`   ✅ Upload concluído!`);
      } catch (uploadErr: any) {
        console.log(`   ⚠️  Upload falhou:`, uploadErr.message);
      }
    }

    await prisma.article.update({
      where: { id: article.id },
      data: { imageUrl: finalImageUrl },
    });

    console.log(`   💾 Salvo no banco!`);
    
    return { success: true };
    
  } catch (error: any) {
    console.error(`   ❌ Erro:`, error.message);
    return { success: false, error: error.message };
  }
}

async function main() {
  console.log("🚀 AUTO-REGENERAÇÃO DE IMAGENS\n");

  try {
    const articles = await prisma.article.findMany({
      select: {
        id: true,
        title: true,
        slug: true,
        imageUrl: true,
      },
      orderBy: { createdAt: 'desc' },
    });

    const brokenArticles = articles.filter(a => 
      a.imageUrl && (a.imageUrl.startsWith('/uploads/') || a.imageUrl.startsWith('data:'))
    );

    console.log(`📊 Artigos: ${articles.length}`);
    console.log(`❌ Quebrados: ${brokenArticles.length}\n`);

    if (brokenArticles.length === 0) {
      console.log("✅ Nenhum artigo precisa de imagem!\n");
      return;
    }

    console.log(`⏱️  Tempo estimado: ~${Math.ceil(brokenArticles.length * 90 / 60)} minutos\n`);

    let success = 0;
    let failed = 0;

    for (let i = 0; i < brokenArticles.length; i++) {
      console.log(`\n[${i + 1}/${brokenArticles.length}]`);
      
      const result = await generateImageForArticle(brokenArticles[i]);
      
      if (result.success) success++;
      else failed++;

      if (i < brokenArticles.length - 1) {
        console.log(`\n   ⏸️  Aguardando 3s...`);
        await new Promise(resolve => setTimeout(resolve, 3000));
      }
    }

    console.log("\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log("📊 RESULTADO:\n");
    console.log(`   ✅ Sucesso: ${success}/${brokenArticles.length}`);
    console.log(`   ❌ Falhas: ${failed}/${brokenArticles.length}\n`);

  } catch (error) {
    console.error("\n❌ Erro fatal:", error);
  } finally {
    await prisma.$disconnect();
  }
}

main();
